"""Golden-set evaluation and gate-fixture generation.

Scores every golden statement with the exported ONNX model (fp32 and INT8),
checks the card's acceptance criteria at the shipped band, and writes the
committed fixture the Go eval gate replays offline:

- accuracy against the human labels, per variant;
- agreement with the recorded LLM-gate verdicts on statements the local
  classifier decides outside the band (the >= 95 percent criterion);
- the fraction of statements routed to the LLM, i.e. scores inside the band
  (the <= 20 percent criterion).
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path

from .dataset import LABEL_CLAIM, load_golden


@dataclass
class EvaluateConfig:
    golden_path: Path
    export_dir: Path
    fixture_path: Path
    band_low: float = 0.35
    band_high: float = 0.75
    llm_labels_path: Path | None = None


def positive_probability(neg: float, pos: float) -> float:
    m = max(neg, pos)
    en = math.exp(neg - m)
    ep = math.exp(pos - m)
    return ep / (en + ep)


def score_all(model_path: Path, tokenizer_dir: Path, texts: list[str]) -> list[float]:
    import numpy as np
    import onnxruntime
    from transformers import AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(tokenizer_dir)
    session = onnxruntime.InferenceSession(str(model_path), providers=["CPUExecutionProvider"])
    input_names = {i.name for i in session.get_inputs()}
    scores: list[float] = []
    for text in texts:
        batch = tokenizer(text, truncation=True, max_length=128, return_tensors="np")
        feeds = {name: batch[name].astype(np.int64) for name in input_names}
        logits = session.run(None, feeds)[0][0]
        scores.append(positive_probability(float(logits[0]), float(logits[1])))
    return scores


def band_metrics(scores: list[float], labels: list[int], llm_labels: list[bool] | None, low: float, high: float) -> dict:
    outside = [i for i, s in enumerate(scores) if s < low or s >= high]
    in_band = [i for i, s in enumerate(scores) if low <= s < high]
    decisions = {i: scores[i] >= high for i in outside}

    accuracy = sum(1 for i, s in enumerate(scores) if (s >= 0.5) == (labels[i] == LABEL_CLAIM)) / len(scores)
    outside_accuracy = (
        sum(1 for i in outside if decisions[i] == (labels[i] == LABEL_CLAIM)) / len(outside) if outside else 1.0
    )
    agreement = None
    if llm_labels is not None:
        agreement = (
            sum(1 for i in outside if decisions[i] == llm_labels[i]) / len(outside) if outside else 1.0
        )
    return {
        "accuracy": accuracy,
        "outside_band_accuracy": outside_accuracy,
        "outside_band_llm_agreement": agreement,
        "llm_call_rate": len(in_band) / len(scores),
        "outside_count": len(outside),
        "in_band_count": len(in_band),
    }


def run(cfg: EvaluateConfig) -> dict:
    golden = load_golden(cfg.golden_path)
    texts = [g.text for g in golden]
    labels = [g.label for g in golden]

    llm_labels: list[bool] | None = None
    if cfg.llm_labels_path and cfg.llm_labels_path.exists():
        recorded = json.loads(cfg.llm_labels_path.read_text())
        if len(recorded) != len(texts):
            raise ValueError(f"llm labels count {len(recorded)} does not match golden count {len(texts)}")
        llm_labels = [bool(v) for v in recorded]

    tokenizer_dir = cfg.export_dir / "onnx"
    fp32_scores = score_all(cfg.export_dir / "onnx" / "model.onnx", tokenizer_dir, texts)
    int8_scores = score_all(cfg.export_dir / "model.int8.onnx", tokenizer_dir, texts)

    report = {
        "band_low": cfg.band_low,
        "band_high": cfg.band_high,
        "golden_size": len(texts),
        "fp32": band_metrics(fp32_scores, labels, llm_labels, cfg.band_low, cfg.band_high),
        "int8": band_metrics(int8_scores, labels, llm_labels, cfg.band_low, cfg.band_high),
    }

    rows = []
    for i, g in enumerate(golden):
        row = {
            "text": g.text,
            "label": "claim" if labels[i] == LABEL_CLAIM else "not_claim",
            "score": round(int8_scores[i], 6),
            "score_fp32": round(fp32_scores[i], 6),
        }
        if llm_labels is not None:
            row["llm_gate"] = llm_labels[i]
        rows.append(row)
    fixture = {
        "about": "Golden gate set for the local check-worthiness classifier (VER-225). "
        "score is the shipped INT8 artifact's calibrated probability; llm_gate is the recorded "
        "generative-gate verdict under the production French prompt. Regenerated by the training "
        "pipeline (stack/ml/checkworthy); never edited by hand.",
        "band_low": cfg.band_low,
        "band_high": cfg.band_high,
        "cases": rows,
    }
    cfg.fixture_path.parent.mkdir(parents=True, exist_ok=True)
    cfg.fixture_path.write_text(json.dumps(fixture, indent=2, ensure_ascii=False) + "\n")
    return report
