-- PDF documents as first-class records (VER-178). A document maps one storage
-- object (documents/{id}/original.pdf) to its upload lifecycle and its
-- persisted fact-check analysis state. Sentences are extracted once in the
-- browser at upload time (same pdf.js engine as the viewer, so highlight
-- anchoring is deterministic) and reused by every analysis run; claims are the
-- per-run verdicts, wiped and rewritten on reanalysis.
CREATE TABLE documents (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title               text NOT NULL,
    object_key          text NOT NULL UNIQUE,
    content_type        text NOT NULL,
    size_bytes          bigint NOT NULL,
    -- Page total reported by the browser extraction; 0 until it is stored.
    page_count          int NOT NULL DEFAULT 0,
    -- Upload lifecycle, mirroring videos.status.
    status              text NOT NULL CHECK (status IN ('pending', 'ready', 'failed')),
    -- Analysis lifecycle; 'analysing' doubles as the job lock.
    analysis_status     text NOT NULL DEFAULT 'none'
                        CHECK (analysis_status IN ('none', 'analysing', 'complete', 'failed')),
    analysis_error      text NOT NULL DEFAULT '',
    -- Progress counters, persisted so progress survives a page refresh.
    sentences_total     int NOT NULL DEFAULT 0,
    sentences_processed int NOT NULL DEFAULT 0,
    analyzed_at         timestamptz,
    analysis_runs       int NOT NULL DEFAULT 0,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- The library lists newest first.
CREATE INDEX documents_created_at_idx ON documents (created_at DESC);

-- Extracted sentences in document order. text is normalized by the browser
-- extraction with the exact rules the viewer applies at anchor time; occurrence
-- is the nth identical sentence text on that page (1-based), disambiguating
-- duplicates. skip_reason follows the segment_results convention: empty means
-- the sentence produced claims (or has not been analysed), and it is rewritten
-- on each analysis run.
CREATE TABLE document_sentences (
    document_id uuid NOT NULL REFERENCES documents (id) ON DELETE CASCADE,
    seq         int NOT NULL,
    page        int NOT NULL CHECK (page >= 1),
    text        text NOT NULL,
    occurrence  int NOT NULL DEFAULT 1 CHECK (occurrence >= 1),
    skip_reason text NOT NULL DEFAULT '' CHECK (skip_reason IN ('', 'not_a_claim', 'not_covered')),
    PRIMARY KEY (document_id, seq)
);

-- Per-run claim verdicts. The enum vocabulary mirrors the verify path's wire
-- shape: status has no 'unchecked' (a batch job blocks on backpressure instead
-- of shedding); verdict/basis/literal are empty-string when the axis does not
-- apply (error claims, credibility-only runs), matching the domain models'
-- empty-string convention. citations is []domain.SegmentMatch in the live wire
-- format so the frontend reuses its verdict components unchanged.
CREATE TABLE document_claims (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id  uuid NOT NULL REFERENCES documents (id) ON DELETE CASCADE,
    sentence_seq int NOT NULL,
    -- Insertion order within the document: created_at is transaction-stable
    -- (one analysis run writes many claims in one transaction), so reads order
    -- by this identity instead to keep a sentence's claims in the order the
    -- analyzer produced them.
    ordinal      bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    claim_id     text NOT NULL,
    text         text NOT NULL,
    status       text NOT NULL CHECK (status IN ('verified', 'error')),
    source       text NOT NULL DEFAULT '' CHECK (source IN ('', 'curated', 'verified')),
    verdict      text NOT NULL DEFAULT '' CHECK (verdict IN ('', 'credible', 'disputed', 'unverifiable')),
    basis        text NOT NULL DEFAULT '' CHECK (basis IN ('', 'evidence', 'knowledge')),
    literal      text NOT NULL DEFAULT '' CHECK (literal IN ('', 'accurate', 'inaccurate', 'unverifiable')),
    flags        text[] NOT NULL DEFAULT '{}',
    confidence   float8 NOT NULL DEFAULT 0,
    rationale    text NOT NULL DEFAULT '',
    citations    jsonb NOT NULL DEFAULT '[]',
    created_at   timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (document_id, sentence_seq)
        REFERENCES document_sentences (document_id, seq) ON DELETE CASCADE
);

-- The claims endpoint reads a document's claims in document order.
CREATE INDEX document_claims_document_idx ON document_claims (document_id, sentence_seq);
