// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertDocumentClaim = `-- name: InsertDocumentClaim :batchexec
INSERT INTO document_claims (document_id, sentence_seq, claim_id, text, status, source, verdict, basis, literal, flags, confidence, rationale, citations)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertDocumentClaimBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertDocumentClaimParams struct {
	DocumentID  uuid.UUID
	SentenceSeq int32
	ClaimID     string
	Text        string
	Status      string
	Source      string
	Verdict     string
	Basis       string
	Literal     string
	Flags       []string
	Confidence  float64
	Rationale   string
	Citations   []byte
}

// Persist one atomic claim's verdict. ordinal is assigned by the identity
// column, preserving insertion order within the sentence.
func (q *Queries) InsertDocumentClaim(ctx context.Context, arg []InsertDocumentClaimParams) *InsertDocumentClaimBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.DocumentID,
			a.SentenceSeq,
			a.ClaimID,
			a.Text,
			a.Status,
			a.Source,
			a.Verdict,
			a.Basis,
			a.Literal,
			a.Flags,
			a.Confidence,
			a.Rationale,
			a.Citations,
		}
		batch.Queue(insertDocumentClaim, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertDocumentClaimBatchResults{br, len(arg), false}
}

func (b *InsertDocumentClaimBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertDocumentClaimBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertDocumentSentence = `-- name: InsertDocumentSentence :batchexec
INSERT INTO document_sentences (document_id, seq, page, text, occurrence)
VALUES ($1, $2, $3, $4, $5)
`

type InsertDocumentSentenceBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertDocumentSentenceParams struct {
	DocumentID uuid.UUID
	Seq        int32
	Page       int32
	Text       string
	Occurrence int32
}

func (q *Queries) InsertDocumentSentence(ctx context.Context, arg []InsertDocumentSentenceParams) *InsertDocumentSentenceBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.DocumentID,
			a.Seq,
			a.Page,
			a.Text,
			a.Occurrence,
		}
		batch.Queue(insertDocumentSentence, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertDocumentSentenceBatchResults{br, len(arg), false}
}

func (b *InsertDocumentSentenceBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertDocumentSentenceBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const setEvidenceChunkClustering = `-- name: SetEvidenceChunkClustering :batchexec
UPDATE evidence_chunks
SET metadata = metadata || jsonb_build_object(
        'cluster_id', $1::integer,
        'importance', $2::double precision)
WHERE source = $3
  AND external_id = $4
  AND chunk_index = $5::integer
`

type SetEvidenceChunkClusteringBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type SetEvidenceChunkClusteringParams struct {
	ClusterID  int32
	Importance float64
	Source     string
	ExternalID string
	ChunkIndex int32
}

// The clustering job writes each chunk's cluster id and importance into the
// metadata jsonb, merging with the || operator so the revision id and section
// keys survive. The casts pin the params to plain integer/double so a non-null
// write is a value, not a nullable pointer.
func (q *Queries) SetEvidenceChunkClustering(ctx context.Context, arg []SetEvidenceChunkClusteringParams) *SetEvidenceChunkClusteringBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ClusterID,
			a.Importance,
			a.Source,
			a.ExternalID,
			a.ChunkIndex,
		}
		batch.Queue(setEvidenceChunkClustering, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &SetEvidenceChunkClusteringBatchResults{br, len(arg), false}
}

func (b *SetEvidenceChunkClusteringBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *SetEvidenceChunkClusteringBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const setEvidenceChunkEmbedding = `-- name: SetEvidenceChunkEmbedding :batchexec
UPDATE evidence_chunks
SET embedding = $1, synced_at = now()
WHERE source = $2 AND external_id = $3 AND chunk_index = $4
`

type SetEvidenceChunkEmbeddingBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type SetEvidenceChunkEmbeddingParams struct {
	Embedding  *pgvector.HalfVector
	Source     string
	ExternalID string
	ChunkIndex int32
}

// Delta sync writes embeddings straight into the live table: at delta volume the
// HNSW index absorbs the inserts incrementally, so no staging swap is needed.
func (q *Queries) SetEvidenceChunkEmbedding(ctx context.Context, arg []SetEvidenceChunkEmbeddingParams) *SetEvidenceChunkEmbeddingBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Embedding,
			a.Source,
			a.ExternalID,
			a.ChunkIndex,
		}
		batch.Queue(setEvidenceChunkEmbedding, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &SetEvidenceChunkEmbeddingBatchResults{br, len(arg), false}
}

func (b *SetEvidenceChunkEmbeddingBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *SetEvidenceChunkEmbeddingBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const trimEvidenceDocumentChunks = `-- name: TrimEvidenceDocumentChunks :batchexec
DELETE FROM evidence_chunks WHERE source = $1 AND external_id = $2 AND chunk_index >= $3
`

type TrimEvidenceDocumentChunksBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type TrimEvidenceDocumentChunksParams struct {
	Source     string
	ExternalID string
	ChunkIndex int32
}

// Removes the stale tail of a document after a re-sync produced fewer chunks
// (from_index 0 removes the document entirely, e.g. it became a redirect).
func (q *Queries) TrimEvidenceDocumentChunks(ctx context.Context, arg []TrimEvidenceDocumentChunksParams) *TrimEvidenceDocumentChunksBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Source,
			a.ExternalID,
			a.ChunkIndex,
		}
		batch.Queue(trimEvidenceDocumentChunks, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &TrimEvidenceDocumentChunksBatchResults{br, len(arg), false}
}

func (b *TrimEvidenceDocumentChunksBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *TrimEvidenceDocumentChunksBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertClaim = `-- name: UpsertClaim :batchexec
INSERT INTO claims (id, content, verdict, sources, embedding)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
    SET content = EXCLUDED.content,
        verdict = EXCLUDED.verdict,
        sources = EXCLUDED.sources,
        embedding = EXCLUDED.embedding
`

type UpsertClaimBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertClaimParams struct {
	ID        string
	Content   string
	Verdict   string
	Sources   []byte
	Embedding pgvector.HalfVector
}

func (q *Queries) UpsertClaim(ctx context.Context, arg []UpsertClaimParams) *UpsertClaimBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Content,
			a.Verdict,
			a.Sources,
			a.Embedding,
		}
		batch.Queue(upsertClaim, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertClaimBatchResults{br, len(arg), false}
}

func (b *UpsertClaimBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertClaimBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertEvidenceChunk = `-- name: UpsertEvidenceChunk :batchexec
INSERT INTO evidence_chunks (source, external_id, chunk_index, title, url, content, kind, metadata, published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (source, external_id, chunk_index) DO UPDATE
    SET title = EXCLUDED.title,
        url = EXCLUDED.url,
        content = EXCLUDED.content,
        kind = EXCLUDED.kind,
        metadata = evidence_chunks.metadata || EXCLUDED.metadata,
        published_at = EXCLUDED.published_at,
        embedding = CASE
            WHEN evidence_chunks.content = EXCLUDED.content THEN evidence_chunks.embedding
            ELSE NULL
        END,
        synced_at = now()
`

type UpsertEvidenceChunkBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertEvidenceChunkParams struct {
	Source      string
	ExternalID  string
	ChunkIndex  int32
	Title       string
	Url         string
	Content     string
	Kind        string
	Metadata    []byte
	PublishedAt pgtype.Timestamptz
}

// Ingest never writes embeddings; the CASE keeps an existing embedding only
// while the content it was computed from is unchanged, so re-ingesting a
// changed revision invalidates the stale vector instead of serving it. metadata
// MERGES (`existing || new`) rather than replacing, so the ingest keys the
// writer supplies (revision id, section) overwrite while the offline clustering
// keys (cluster_id, importance) the ingest does not carry survive a re-ingest -
// the old schema kept importance in a dedicated column the upsert never touched,
// and UnembeddedLive reads that importance to embed the most important content
// first.
func (q *Queries) UpsertEvidenceChunk(ctx context.Context, arg []UpsertEvidenceChunkParams) *UpsertEvidenceChunkBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Source,
			a.ExternalID,
			a.ChunkIndex,
			a.Title,
			a.Url,
			a.Content,
			a.Kind,
			a.Metadata,
			a.PublishedAt,
		}
		batch.Queue(upsertEvidenceChunk, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertEvidenceChunkBatchResults{br, len(arg), false}
}

func (b *UpsertEvidenceChunkBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertEvidenceChunkBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
