// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	pgvector "github.com/pgvector/pgvector-go"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertClaim = `-- name: UpsertClaim :batchexec
INSERT INTO claims (id, content, verdict, sources, embedding)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
    SET content = EXCLUDED.content,
        verdict = EXCLUDED.verdict,
        sources = EXCLUDED.sources,
        embedding = EXCLUDED.embedding
`

type UpsertClaimBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertClaimParams struct {
	ID        string
	Content   string
	Verdict   string
	Sources   []byte
	Embedding pgvector.HalfVector
}

func (q *Queries) UpsertClaim(ctx context.Context, arg []UpsertClaimParams) *UpsertClaimBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Content,
			a.Verdict,
			a.Sources,
			a.Embedding,
		}
		batch.Queue(upsertClaim, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertClaimBatchResults{br, len(arg), false}
}

func (b *UpsertClaimBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertClaimBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
