// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package db

import (
	"context"

	pgvector "github.com/pgvector/pgvector-go"
)

const searchClaims = `-- name: SearchClaims :many
SELECT id, content, verdict, sources, (embedding <=> $1)::float8 AS distance
FROM claims
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchClaimsParams struct {
	QueryEmbedding pgvector.HalfVector
	ResultLimit    int32
}

type SearchClaimsRow struct {
	ID       string
	Content  string
	Verdict  string
	Sources  []byte
	Distance float64
}

// Named arg query_embedding is referenced twice but sqlc collapses it to a
// single parameter, so the HNSW index still drives the ORDER BY (no repeated
// positional-parameter mis-numbering).
func (q *Queries) SearchClaims(ctx context.Context, arg SearchClaimsParams) ([]SearchClaimsRow, error) {
	rows, err := q.db.Query(ctx, searchClaims, arg.QueryEmbedding, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchClaimsRow{}
	for rows.Next() {
		var i SearchClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Verdict,
			&i.Sources,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
