// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claimchecks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClaimChecksBefore = `-- name: CountClaimChecksBefore :one
SELECT count(*) FROM claim_checks WHERE occurred_at < $1
`

// The retention dry run: how many rows an apply would remove.
func (q *Queries) CountClaimChecksBefore(ctx context.Context, occurredAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimChecksBefore, occurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteClaimChecksBefore = `-- name: DeleteClaimChecksBefore :execrows
DELETE FROM claim_checks WHERE occurred_at < $1
`

// The retention sweep: rows older than the cutoff age out; the occurred_at
// index serves the range delete.
func (q *Queries) DeleteClaimChecksBefore(ctx context.Context, occurredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClaimChecksBefore, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listClaimChecksSince = `-- name: ListClaimChecksSince :many
SELECT occurred_at, session_kind, locale, speaker, unit_text, claim_text,
       decision_path, skip_reason,
       retrieval_top, retrieval_candidates, retrieval_claim_hits, retrieval_evidence_hits,
       verdict, basis, literal, confidence, source,
       escalated, llm_calls, latency_ms
FROM claim_checks
WHERE occurred_at >= $1
ORDER BY occurred_at, id
`

type ListClaimChecksSinceRow struct {
	OccurredAt            pgtype.Timestamptz
	SessionKind           string
	Locale                string
	Speaker               string
	UnitText              string
	ClaimText             string
	DecisionPath          string
	SkipReason            string
	RetrievalTop          float64
	RetrievalCandidates   int32
	RetrievalClaimHits    int32
	RetrievalEvidenceHits int32
	Verdict               string
	Basis                 string
	Literal               string
	Confidence            float64
	Source                string
	Escalated             bool
	LlmCalls              int32
	LatencyMs             int64
}

// Dataset builds and tests read recent rows oldest-first; the occurred_at
// index serves the range scan.
func (q *Queries) ListClaimChecksSince(ctx context.Context, occurredAt pgtype.Timestamptz) ([]ListClaimChecksSinceRow, error) {
	rows, err := q.db.Query(ctx, listClaimChecksSince, occurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimChecksSinceRow{}
	for rows.Next() {
		var i ListClaimChecksSinceRow
		if err := rows.Scan(
			&i.OccurredAt,
			&i.SessionKind,
			&i.Locale,
			&i.Speaker,
			&i.UnitText,
			&i.ClaimText,
			&i.DecisionPath,
			&i.SkipReason,
			&i.RetrievalTop,
			&i.RetrievalCandidates,
			&i.RetrievalClaimHits,
			&i.RetrievalEvidenceHits,
			&i.Verdict,
			&i.Basis,
			&i.Literal,
			&i.Confidence,
			&i.Source,
			&i.Escalated,
			&i.LlmCalls,
			&i.LatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
