// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, title, object_key, content_type, size_bytes, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, object_key, content_type, size_bytes, page_count, status, analysis_status, analysis_error, sentences_total, sentences_processed, analyzed_at, analysis_runs, created_at, updated_at
`

type CreateDocumentParams struct {
	ID          uuid.UUID
	Title       string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Status      string
}

// The id is caller-minted (the object key embeds it), unlike videos whose id
// the database assigns.
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.Title,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.PageCount,
		&i.Status,
		&i.AnalysisStatus,
		&i.AnalysisError,
		&i.SentencesTotal,
		&i.SentencesProcessed,
		&i.AnalyzedAt,
		&i.AnalysisRuns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents
WHERE id = $1
`

// Sentences and claims go with the document via ON DELETE CASCADE.
func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, object_key, content_type, size_bytes, page_count, status, analysis_status, analysis_error, sentences_total, sentences_processed, analyzed_at, analysis_runs, created_at, updated_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.PageCount,
		&i.Status,
		&i.AnalysisStatus,
		&i.AnalysisError,
		&i.SentencesTotal,
		&i.SentencesProcessed,
		&i.AnalyzedAt,
		&i.AnalysisRuns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentClaims = `-- name: ListDocumentClaims :many
SELECT id, document_id, sentence_seq, claim_id, text, status, source, verdict, basis, literal, flags, confidence, rationale, citations, created_at
FROM document_claims
WHERE document_id = $1
ORDER BY sentence_seq, ordinal
`

type ListDocumentClaimsRow struct {
	ID          uuid.UUID
	DocumentID  uuid.UUID
	SentenceSeq int32
	ClaimID     string
	Text        string
	Status      string
	Source      string
	Verdict     string
	Basis       string
	Literal     string
	Flags       []string
	Confidence  float64
	Rationale   string
	Citations   []byte
	CreatedAt   pgtype.Timestamptz
}

// ordinal, not created_at, carries insertion order: an analysis run writes its
// claims in one transaction, so their created_at values are identical.
func (q *Queries) ListDocumentClaims(ctx context.Context, documentID uuid.UUID) ([]ListDocumentClaimsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentClaims, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentClaimsRow{}
	for rows.Next() {
		var i ListDocumentClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SentenceSeq,
			&i.ClaimID,
			&i.Text,
			&i.Status,
			&i.Source,
			&i.Verdict,
			&i.Basis,
			&i.Literal,
			&i.Flags,
			&i.Confidence,
			&i.Rationale,
			&i.Citations,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentSentences = `-- name: ListDocumentSentences :many
SELECT document_id, seq, page, text, occurrence, skip_reason
FROM document_sentences
WHERE document_id = $1
ORDER BY seq
`

func (q *Queries) ListDocumentSentences(ctx context.Context, documentID uuid.UUID) ([]DocumentSentence, error) {
	rows, err := q.db.Query(ctx, listDocumentSentences, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentSentence{}
	for rows.Next() {
		var i DocumentSentence
		if err := rows.Scan(
			&i.DocumentID,
			&i.Seq,
			&i.Page,
			&i.Text,
			&i.Occurrence,
			&i.SkipReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT d.id, d.title, d.object_key, d.content_type, d.size_bytes, d.page_count, d.status, d.analysis_status, d.analysis_error, d.sentences_total, d.sentences_processed, d.analyzed_at, d.analysis_runs, d.created_at, d.updated_at,
       count(c.id) FILTER (WHERE c.verdict = 'credible') AS credible_claims,
       count(c.id) FILTER (WHERE c.verdict = 'disputed') AS disputed_claims
FROM documents d
LEFT JOIN document_claims c ON c.document_id = d.id
GROUP BY d.id
ORDER BY d.created_at DESC, d.id
`

type ListDocumentsRow struct {
	Document       Document
	CredibleClaims int64
	DisputedClaims int64
}

// Library rows, newest first, each with its verdict summary counts. The FILTER
// counts read stored claims only; a document with no claims counts zero.
// sqlc.embed keeps the row a real db.Document, so a future documents column
// cannot silently drop out of the list mapping.
func (q *Queries) ListDocuments(ctx context.Context) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.Document.ID,
			&i.Document.Title,
			&i.Document.ObjectKey,
			&i.Document.ContentType,
			&i.Document.SizeBytes,
			&i.Document.PageCount,
			&i.Document.Status,
			&i.Document.AnalysisStatus,
			&i.Document.AnalysisError,
			&i.Document.SentencesTotal,
			&i.Document.SentencesProcessed,
			&i.Document.AnalyzedAt,
			&i.Document.AnalysisRuns,
			&i.Document.CreatedAt,
			&i.Document.UpdatedAt,
			&i.CredibleClaims,
			&i.DisputedClaims,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentExtracted = `-- name: SetDocumentExtracted :one
UPDATE documents
SET page_count = $2, sentences_total = $3, status = 'ready', updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, title, object_key, content_type, size_bytes, page_count, status, analysis_status, analysis_error, sentences_total, sentences_processed, analyzed_at, analysis_runs, created_at, updated_at
`

type SetDocumentExtractedParams struct {
	ID             uuid.UUID
	PageCount      int32
	SentencesTotal int32
}

// Flip a pending document to ready with its extraction metadata. The status
// guard makes extraction exactly-once: a non-pending document returns no row
// and the store maps that to a conflict.
func (q *Queries) SetDocumentExtracted(ctx context.Context, arg SetDocumentExtractedParams) (Document, error) {
	row := q.db.QueryRow(ctx, setDocumentExtracted, arg.ID, arg.PageCount, arg.SentencesTotal)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.PageCount,
		&i.Status,
		&i.AnalysisStatus,
		&i.AnalysisError,
		&i.SentencesTotal,
		&i.SentencesProcessed,
		&i.AnalyzedAt,
		&i.AnalysisRuns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
