// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	pgvector "github.com/pgvector/pgvector-go"
)

const searchDocuments = `-- name: SearchDocuments :many
SELECT id, content, metadata, (embedding <=> $1)::float8 AS distance
FROM documents
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchDocumentsParams struct {
	QueryEmbedding pgvector.HalfVector
	ResultLimit    int32
}

type SearchDocumentsRow struct {
	ID       string
	Content  string
	Metadata []byte
	Distance float64
}

// Named arg query_embedding is referenced twice but sqlc collapses it to a
// single parameter, so the HNSW index still drives the ORDER BY (no repeated
// positional-parameter mis-numbering).
func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments, arg.QueryEmbedding, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsRow{}
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Metadata,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
