// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const acquireEvidenceSourceLock = `-- name: AcquireEvidenceSourceLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Transaction-scoped advisory lock serializing source claims, so two concurrent
// syncs cannot both pass the foreign-source check and claim different sources.
// Released automatically at commit/rollback.
func (q *Queries) AcquireEvidenceSourceLock(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, acquireEvidenceSourceLock, key)
	return err
}

const claimEvidenceSource = `-- name: ClaimEvidenceSource :exec
INSERT INTO evidence_sync_state (source) VALUES ($1)
ON CONFLICT (source) DO NOTHING
`

// Claims the store for a source before ingestion starts (and before any
// checkpoint exists), so a source switch is detectable even after a crashed
// first run. Never overwrites an existing checkpoint.
func (q *Queries) ClaimEvidenceSource(ctx context.Context, source string) error {
	_, err := q.db.Exec(ctx, claimEvidenceSource, source)
	return err
}

const countEvidenceChunksForDocument = `-- name: CountEvidenceChunksForDocument :one
SELECT count(*) FROM evidence_chunks WHERE source = $1 AND external_id = $2
`

type CountEvidenceChunksForDocumentParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) CountEvidenceChunksForDocument(ctx context.Context, arg CountEvidenceChunksForDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEvidenceChunksForDocument, arg.Source, arg.ExternalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvidenceDocuments = `-- name: CountEvidenceDocuments :one
SELECT count(DISTINCT (source, external_id))::bigint
FROM evidence_chunks
WHERE source <> ALL($1::text[])
`

// The delta-sync bulk-recommendation denominator counts only the encyclopedic
// corpora: every statistical source (separate sources that share this table) is
// excluded so its rows never skew the change-fraction guard. A document is one
// (source, external_id).
func (q *Queries) CountEvidenceDocuments(ctx context.Context, excludeSources []string) (int64, error) {
	row := q.db.QueryRow(ctx, countEvidenceDocuments, excludeSources)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteEvidenceByTitle = `-- name: DeleteEvidenceByTitle :exec
DELETE FROM evidence_chunks
WHERE source = $1 AND title = ANY($2::text[])
`

type DeleteEvidenceByTitleParams struct {
	Source string
	Titles []string
}

// Delta sync removes a hard-deleted page by title within its own source:
// RecentChanges reports a deletion with page id 0, so the stored chunk can only
// be found by its title. Scoping to the source keeps a same-titled chunk of
// another source safe.
func (q *Queries) DeleteEvidenceByTitle(ctx context.Context, arg DeleteEvidenceByTitleParams) error {
	_, err := q.db.Exec(ctx, deleteEvidenceByTitle, arg.Source, arg.Titles)
	return err
}

const deleteEvidenceDocument = `-- name: DeleteEvidenceDocument :exec
DELETE FROM evidence_chunks WHERE source = $1 AND external_id = $2
`

type DeleteEvidenceDocumentParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) DeleteEvidenceDocument(ctx context.Context, arg DeleteEvidenceDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteEvidenceDocument, arg.Source, arg.ExternalID)
	return err
}

const embeddedEvidenceChunks = `-- name: EmbeddedEvidenceChunks :many
SELECT source, external_id, chunk_index, embedding
FROM evidence_chunks
WHERE embedding IS NOT NULL
  AND source <> ALL($1::text[])
  AND (source, external_id, chunk_index) > ($2::text, $3::text, $4::integer)
ORDER BY source, external_id, chunk_index
LIMIT $5
`

type EmbeddedEvidenceChunksParams struct {
	ExcludeSources  []string
	AfterSource     string
	AfterExternalID string
	AfterChunkIndex int32
	RowLimit        int32
}

type EmbeddedEvidenceChunksRow struct {
	Source     string
	ExternalID string
	ChunkIndex int32
	Embedding  *pgvector.HalfVector
}

// The clustering job reads the embedded live corpus in keyset order to group it
// into topic clusters and score importance. The embedding IS NOT NULL filter
// scopes the scan to the chunks that actually carry a vector to cluster, and the
// source filter keeps statistical evidence (separate sources sharing this table)
// out of the encyclopedic clustering it does not belong to.
func (q *Queries) EmbeddedEvidenceChunks(ctx context.Context, arg EmbeddedEvidenceChunksParams) ([]EmbeddedEvidenceChunksRow, error) {
	rows, err := q.db.Query(ctx, embeddedEvidenceChunks,
		arg.ExcludeSources,
		arg.AfterSource,
		arg.AfterExternalID,
		arg.AfterChunkIndex,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbeddedEvidenceChunksRow{}
	for rows.Next() {
		var i EmbeddedEvidenceChunksRow
		if err := rows.Scan(
			&i.Source,
			&i.ExternalID,
			&i.ChunkIndex,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvidenceChunk = `-- name: GetEvidenceChunk :one
SELECT source, external_id, chunk_index, title, url, content, kind, metadata,
       (embedding IS NULL)::boolean AS embedding_is_null
FROM evidence_chunks
WHERE source = $1 AND external_id = $2 AND chunk_index = $3
`

type GetEvidenceChunkParams struct {
	Source     string
	ExternalID string
	ChunkIndex int32
}

type GetEvidenceChunkRow struct {
	Source          string
	ExternalID      string
	ChunkIndex      int32
	Title           string
	Url             string
	Content         string
	Kind            string
	Metadata        []byte
	EmbeddingIsNull bool
}

func (q *Queries) GetEvidenceChunk(ctx context.Context, arg GetEvidenceChunkParams) (GetEvidenceChunkRow, error) {
	row := q.db.QueryRow(ctx, getEvidenceChunk, arg.Source, arg.ExternalID, arg.ChunkIndex)
	var i GetEvidenceChunkRow
	err := row.Scan(
		&i.Source,
		&i.ExternalID,
		&i.ChunkIndex,
		&i.Title,
		&i.Url,
		&i.Content,
		&i.Kind,
		&i.Metadata,
		&i.EmbeddingIsNull,
	)
	return i, err
}

const getEvidenceSyncState = `-- name: GetEvidenceSyncState :one
SELECT source, last_change_ts, dump_version, synced_at
FROM evidence_sync_state
WHERE source = $1
`

func (q *Queries) GetEvidenceSyncState(ctx context.Context, source string) (EvidenceSyncState, error) {
	row := q.db.QueryRow(ctx, getEvidenceSyncState, source)
	var i EvidenceSyncState
	err := row.Scan(
		&i.Source,
		&i.LastChangeTs,
		&i.DumpVersion,
		&i.SyncedAt,
	)
	return i, err
}

const getOtherEvidenceSource = `-- name: GetOtherEvidenceSource :one
SELECT source FROM evidence_sync_state WHERE source <> $1 LIMIT 1
`

func (q *Queries) GetOtherEvidenceSource(ctx context.Context, source string) (string, error) {
	row := q.db.QueryRow(ctx, getOtherEvidenceSource, source)
	var source_2 string
	err := row.Scan(&source_2)
	return source_2, err
}

const searchEvidenceChunks = `-- name: SearchEvidenceChunks :many
SELECT source, external_id, chunk_index, title, url, content, kind, metadata,
       (embedding <=> $1)::float8 AS distance
FROM evidence_chunks
WHERE embedding IS NOT NULL
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchEvidenceChunksParams struct {
	QueryEmbedding *pgvector.HalfVector
	ResultLimit    int32
}

type SearchEvidenceChunksRow struct {
	Source     string
	ExternalID string
	ChunkIndex int32
	Title      string
	Url        string
	Content    string
	Kind       string
	Metadata   []byte
	Distance   float64
}

// Approximate nearest-neighbor retrieval over the embedded corpus, mirroring
// SearchClaims. The embedding IS NOT NULL filter keeps unembedded chunks out of
// the result regardless of the chosen plan; the HNSW index only indexes
// non-null rows, so the filter does not degrade index use. query_embedding is
// referenced twice but sqlc collapses it to one parameter, so the index still
// drives the ORDER BY.
func (q *Queries) SearchEvidenceChunks(ctx context.Context, arg SearchEvidenceChunksParams) ([]SearchEvidenceChunksRow, error) {
	rows, err := q.db.Query(ctx, searchEvidenceChunks, arg.QueryEmbedding, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEvidenceChunksRow{}
	for rows.Next() {
		var i SearchEvidenceChunksRow
		if err := rows.Scan(
			&i.Source,
			&i.ExternalID,
			&i.ChunkIndex,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Kind,
			&i.Metadata,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storedEvidenceRevisions = `-- name: StoredEvidenceRevisions :many
SELECT external_id, COALESCE(max((metadata->>'revision_id')::bigint), 0)::bigint AS revision_id
FROM evidence_chunks
WHERE source = $1 AND external_id = ANY($2::text[])
GROUP BY external_id
`

type StoredEvidenceRevisionsParams struct {
	Source      string
	ExternalIds []string
}

type StoredEvidenceRevisionsRow struct {
	ExternalID string
	RevisionID int64
}

// Delta sync diffs the revision RecentChanges reports against the one stored, so
// a document already at that revision is neither refetched nor re-embedded. A
// document's chunks share a revision after an upsert; max guards a partial
// update. revision_id lives in the metadata jsonb now (a wiki-source key), so a
// row missing the key yields NULL from the ->> and COALESCE floors it to 0 - a
// non-numeric revision the delta always treats as stale and refetches, rather
// than a NULL that would fail the non-nullable int64 scan and stall the sync.
func (q *Queries) StoredEvidenceRevisions(ctx context.Context, arg StoredEvidenceRevisionsParams) ([]StoredEvidenceRevisionsRow, error) {
	rows, err := q.db.Query(ctx, storedEvidenceRevisions, arg.Source, arg.ExternalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoredEvidenceRevisionsRow{}
	for rows.Next() {
		var i StoredEvidenceRevisionsRow
		if err := rows.Scan(&i.ExternalID, &i.RevisionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unembeddedEvidenceChunks = `-- name: UnembeddedEvidenceChunks :many
SELECT source, external_id, chunk_index, title, url, content, kind, metadata
FROM evidence_chunks
WHERE embedding IS NULL
  AND (source, external_id, chunk_index) > ($1::text, $2::text, $3::integer)
ORDER BY source, external_id, chunk_index
LIMIT $4
`

type UnembeddedEvidenceChunksParams struct {
	AfterSource     string
	AfterExternalID string
	AfterChunkIndex int32
	RowLimit        int32
}

type UnembeddedEvidenceChunksRow struct {
	Source     string
	ExternalID string
	ChunkIndex int32
	Title      string
	Url        string
	Content    string
	Kind       string
	Metadata   []byte
}

// The delta sync reads the chunks it just upserted into the live table back in
// keyset order to embed them in place. The embedding IS NULL filter scopes the
// scan to the unembedded chunks a delta run produced. The keyset spans the full
// (source, external_id, chunk_index) because external_id is unique only within a
// source.
func (q *Queries) UnembeddedEvidenceChunks(ctx context.Context, arg UnembeddedEvidenceChunksParams) ([]UnembeddedEvidenceChunksRow, error) {
	rows, err := q.db.Query(ctx, unembeddedEvidenceChunks,
		arg.AfterSource,
		arg.AfterExternalID,
		arg.AfterChunkIndex,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnembeddedEvidenceChunksRow{}
	for rows.Next() {
		var i UnembeddedEvidenceChunksRow
		if err := rows.Scan(
			&i.Source,
			&i.ExternalID,
			&i.ChunkIndex,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Kind,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbeddedEvidenceChunk = `-- name: UpsertEmbeddedEvidenceChunk :exec
INSERT INTO evidence_chunks (source, external_id, chunk_index, title, url, content, kind, metadata, embedding, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (source, external_id, chunk_index) DO UPDATE
    SET title = EXCLUDED.title,
        url = EXCLUDED.url,
        content = EXCLUDED.content,
        kind = EXCLUDED.kind,
        metadata = evidence_chunks.metadata || EXCLUDED.metadata,
        embedding = EXCLUDED.embedding,
        synced_at = now()
`

type UpsertEmbeddedEvidenceChunkParams struct {
	Source     string
	ExternalID string
	ChunkIndex int32
	Title      string
	Url        string
	Content    string
	Kind       string
	Metadata   []byte
	Embedding  *pgvector.HalfVector
}

// Crawl ingestion writes content and embedding together: the worker embeds the
// self-contained message, then upserts the whole row in one statement so a chunk
// is never visible to search without its matching vector. The embedding is always
// the freshly computed one, so a re-crawl rewrites the same vector idempotently.
func (q *Queries) UpsertEmbeddedEvidenceChunk(ctx context.Context, arg UpsertEmbeddedEvidenceChunkParams) error {
	_, err := q.db.Exec(ctx, upsertEmbeddedEvidenceChunk,
		arg.Source,
		arg.ExternalID,
		arg.ChunkIndex,
		arg.Title,
		arg.Url,
		arg.Content,
		arg.Kind,
		arg.Metadata,
		arg.Embedding,
	)
	return err
}

const upsertEvidenceSyncState = `-- name: UpsertEvidenceSyncState :exec
INSERT INTO evidence_sync_state (source, last_change_ts, dump_version)
VALUES ($1, $2, $3)
ON CONFLICT (source) DO UPDATE
    SET last_change_ts = EXCLUDED.last_change_ts,
        dump_version = EXCLUDED.dump_version,
        synced_at = now()
`

type UpsertEvidenceSyncStateParams struct {
	Source       string
	LastChangeTs pgtype.Timestamptz
	DumpVersion  pgtype.Text
}

func (q *Queries) UpsertEvidenceSyncState(ctx context.Context, arg UpsertEvidenceSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertEvidenceSyncState, arg.Source, arg.LastChangeTs, arg.DumpVersion)
	return err
}
