// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type Claim struct {
	ID        string
	Content   string
	Verdict   string
	Sources   []byte
	Embedding pgvector.HalfVector
}

type ProcessedVideo struct {
	VideoID      string
	SegmentCount int32
	CompletedAt  pgtype.Timestamptz
}

type SegmentResult struct {
	VideoID    string
	StartMs    int64
	EndMs      int64
	Content    string
	Matches    []byte
	SkipReason string
}

type WikiChunk struct {
	PageID     int64
	ChunkIndex int32
	Title      string
	Url        string
	RevisionID int64
	Corpus     string
	Content    string
	Embedding  *pgvector.HalfVector
	SyncedAt   pgtype.Timestamptz
}

type WikiSyncState struct {
	Corpus       string
	LastChangeTs pgtype.Timestamptz
	DumpVersion  pgtype.Text
	SyncedAt     pgtype.Timestamptz
}
