// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	pgvector "github.com/pgvector/pgvector-go"
)

type Claim struct {
	ID        string
	Content   string
	Verdict   string
	Sources   []byte
	Embedding pgvector.HalfVector
}
