// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type Claim struct {
	ID        string
	Content   string
	Verdict   string
	Sources   []byte
	Embedding pgvector.HalfVector
}

type Document struct {
	ID                 uuid.UUID
	Title              string
	ObjectKey          string
	ContentType        string
	SizeBytes          int64
	PageCount          int32
	Status             string
	AnalysisStatus     string
	AnalysisError      string
	SentencesTotal     int32
	SentencesProcessed int32
	AnalyzedAt         pgtype.Timestamptz
	AnalysisRuns       int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type DocumentClaim struct {
	ID          uuid.UUID
	DocumentID  uuid.UUID
	SentenceSeq int32
	ClaimID     string
	Text        string
	Status      string
	Source      string
	Verdict     string
	Basis       string
	Literal     string
	Flags       []string
	Confidence  float64
	Rationale   string
	Citations   []byte
	CreatedAt   pgtype.Timestamptz
}

type DocumentSentence struct {
	DocumentID uuid.UUID
	Seq        int32
	Page       int32
	Text       string
	Occurrence int32
	SkipReason string
}

type PoliticalClaim struct {
	ID             string
	Content        string
	LiteralVerdict string
	Flags          []string
	SourceName     string
	SourceUrl      string
	QuotedSpan     string
	Outlet         string
	CheckedAt      pgtype.Timestamptz
	Embedding      pgvector.HalfVector
	SyncedAt       pgtype.Timestamptz
}

type Video struct {
	ID          uuid.UUID
	Title       string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Status      string
	Kind        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SourceUrl   pgtype.Text
	SourceID    pgtype.Text
	DurationMs  int64
	Error       pgtype.Text
}

type VotingRecord struct {
	PersonID   string
	PersonName string
	Chamber    string
	ScrutinID  string
	BillTitle  string
	VotedOn    pgtype.Date
	Position   string
	SourceUrl  string
	SyncedAt   pgtype.Timestamptz
}

type WikiChunk struct {
	PageID     int64
	ChunkIndex int32
	Title      string
	Url        string
	RevisionID int64
	Corpus     string
	Content    string
	Embedding  *pgvector.HalfVector
	SyncedAt   pgtype.Timestamptz
	Section    string
	Kind       string
	ClusterID  pgtype.Int4
	Importance pgtype.Float8
}

type WikiSyncState struct {
	Corpus       string
	LastChangeTs pgtype.Timestamptz
	DumpVersion  pgtype.Text
	SyncedAt     pgtype.Timestamptz
}
