// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: political.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const lookupVotingRecords = `-- name: LookupVotingRecords :many
SELECT person_id, person_name, chamber, scrutin_id, bill_title, voted_on, position, source_url
FROM voting_records
WHERE person_id = $1
  AND bill_title = $2
  AND voted_on = $3
ORDER BY scrutin_id
`

type LookupVotingRecordsParams struct {
	PersonID  string
	BillTitle string
	VotedOn   pgtype.Date
}

type LookupVotingRecordsRow struct {
	PersonID   string
	PersonName string
	Chamber    string
	ScrutinID  string
	BillTitle  string
	VotedOn    pgtype.Date
	Position   string
	SourceUrl  string
}

// The voting adapter answers "how did person X vote on bill Y around date Z". The
// predicate order matches voting_records_person_bill_date_idx. The date is an
// exact match on the recorded scrutin date; a caller resolves the scrutin date
// before lookup.
func (q *Queries) LookupVotingRecords(ctx context.Context, arg LookupVotingRecordsParams) ([]LookupVotingRecordsRow, error) {
	rows, err := q.db.Query(ctx, lookupVotingRecords, arg.PersonID, arg.BillTitle, arg.VotedOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LookupVotingRecordsRow{}
	for rows.Next() {
		var i LookupVotingRecordsRow
		if err := rows.Scan(
			&i.PersonID,
			&i.PersonName,
			&i.Chamber,
			&i.ScrutinID,
			&i.BillTitle,
			&i.VotedOn,
			&i.Position,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPoliticalClaims = `-- name: SearchPoliticalClaims :many
SELECT id, content, literal_verdict, flags, source_name, source_url, quoted_span, outlet, checked_at,
       (embedding <=> $1)::float8 AS distance
FROM political_claims
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchPoliticalClaimsParams struct {
	QueryEmbedding pgvector.HalfVector
	ResultLimit    int32
}

type SearchPoliticalClaimsRow struct {
	ID             string
	Content        string
	LiteralVerdict string
	Flags          []string
	SourceName     string
	SourceUrl      string
	QuotedSpan     string
	Outlet         string
	CheckedAt      pgtype.Timestamptz
	Distance       float64
}

// Approximate nearest-neighbor retrieval over the curated political claim DB,
// mirroring SearchClaims: the fast path borrows an instant verdict for a repeated
// talking point. query_embedding is referenced twice but sqlc collapses it to one
// parameter, so the HNSW index drives the ORDER BY.
func (q *Queries) SearchPoliticalClaims(ctx context.Context, arg SearchPoliticalClaimsParams) ([]SearchPoliticalClaimsRow, error) {
	rows, err := q.db.Query(ctx, searchPoliticalClaims, arg.QueryEmbedding, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPoliticalClaimsRow{}
	for rows.Next() {
		var i SearchPoliticalClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.LiteralVerdict,
			&i.Flags,
			&i.SourceName,
			&i.SourceUrl,
			&i.QuotedSpan,
			&i.Outlet,
			&i.CheckedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPoliticalClaim = `-- name: UpsertPoliticalClaim :exec
INSERT INTO political_claims (
    id, content, literal_verdict, flags, source_name, source_url, quoted_span, outlet, checked_at, embedding, synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (id) DO UPDATE
    SET content = EXCLUDED.content,
        literal_verdict = EXCLUDED.literal_verdict,
        flags = EXCLUDED.flags,
        source_name = EXCLUDED.source_name,
        source_url = EXCLUDED.source_url,
        quoted_span = EXCLUDED.quoted_span,
        outlet = EXCLUDED.outlet,
        checked_at = EXCLUDED.checked_at,
        embedding = EXCLUDED.embedding,
        synced_at = now()
`

type UpsertPoliticalClaimParams struct {
	ID             string
	Content        string
	LiteralVerdict string
	Flags          []string
	SourceName     string
	SourceUrl      string
	QuotedSpan     string
	Outlet         string
	CheckedAt      pgtype.Timestamptz
	Embedding      pgvector.HalfVector
}

// The fact-check-archive crawler writes a curated claim with its embedding in one
// statement, so a row is never visible to ANN search without its matching vector.
// The embedding is the freshly computed one, so a re-crawl rewrites the same row
// idempotently. The embedding is bound text-form (::halfvec via the pgvector
// Valuer), never binary COPY.
func (q *Queries) UpsertPoliticalClaim(ctx context.Context, arg UpsertPoliticalClaimParams) error {
	_, err := q.db.Exec(ctx, upsertPoliticalClaim,
		arg.ID,
		arg.Content,
		arg.LiteralVerdict,
		arg.Flags,
		arg.SourceName,
		arg.SourceUrl,
		arg.QuotedSpan,
		arg.Outlet,
		arg.CheckedAt,
		arg.Embedding,
	)
	return err
}

const upsertVotingRecord = `-- name: UpsertVotingRecord :exec
INSERT INTO voting_records (
    person_id, person_name, chamber, scrutin_id, bill_title, voted_on, position, source_url, synced_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (person_id, scrutin_id) DO UPDATE
    SET person_name = EXCLUDED.person_name,
        chamber = EXCLUDED.chamber,
        bill_title = EXCLUDED.bill_title,
        voted_on = EXCLUDED.voted_on,
        position = EXCLUDED.position,
        source_url = EXCLUDED.source_url,
        synced_at = now()
`

type UpsertVotingRecordParams struct {
	PersonID   string
	PersonName string
	Chamber    string
	ScrutinID  string
	BillTitle  string
	VotedOn    pgtype.Date
	Position   string
	SourceUrl  string
}

// Scrutins ingest writes one recorded position per person per scrutin. Re-running
// the ingest rewrites the same row, so a bulk re-run is idempotent.
func (q *Queries) UpsertVotingRecord(ctx context.Context, arg UpsertVotingRecordParams) error {
	_, err := q.db.Exec(ctx, upsertVotingRecord,
		arg.PersonID,
		arg.PersonName,
		arg.Chamber,
		arg.ScrutinID,
		arg.BillTitle,
		arg.VotedOn,
		arg.Position,
		arg.SourceUrl,
	)
	return err
}
