// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processing.sql

package db

import (
	"context"
)

const deleteSegmentResults = `-- name: DeleteSegmentResults :exec
DELETE FROM segment_results
WHERE video_id = $1
`

func (q *Queries) DeleteSegmentResults(ctx context.Context, videoID string) error {
	_, err := q.db.Exec(ctx, deleteSegmentResults, videoID)
	return err
}

const getProcessedVideoSegmentCount = `-- name: GetProcessedVideoSegmentCount :one
SELECT segment_count
FROM processed_videos
WHERE video_id = $1
`

func (q *Queries) GetProcessedVideoSegmentCount(ctx context.Context, videoID string) (int32, error) {
	row := q.db.QueryRow(ctx, getProcessedVideoSegmentCount, videoID)
	var segment_count int32
	err := row.Scan(&segment_count)
	return segment_count, err
}

const listSegmentResults = `-- name: ListSegmentResults :many
SELECT video_id, start_ms, end_ms, content, matches
FROM segment_results
WHERE video_id = $1
ORDER BY start_ms
`

func (q *Queries) ListSegmentResults(ctx context.Context, videoID string) ([]SegmentResult, error) {
	rows, err := q.db.Query(ctx, listSegmentResults, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentResult{}
	for rows.Next() {
		var i SegmentResult
		if err := rows.Scan(
			&i.VideoID,
			&i.StartMs,
			&i.EndMs,
			&i.Content,
			&i.Matches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVideoProcessed = `-- name: MarkVideoProcessed :exec
INSERT INTO processed_videos (video_id, segment_count)
VALUES ($1, $2)
ON CONFLICT (video_id) DO UPDATE
    SET segment_count = EXCLUDED.segment_count,
        completed_at  = now()
`

type MarkVideoProcessedParams struct {
	VideoID      string
	SegmentCount int32
}

func (q *Queries) MarkVideoProcessed(ctx context.Context, arg MarkVideoProcessedParams) error {
	_, err := q.db.Exec(ctx, markVideoProcessed, arg.VideoID, arg.SegmentCount)
	return err
}

const upsertSegmentResult = `-- name: UpsertSegmentResult :exec
INSERT INTO segment_results (video_id, start_ms, end_ms, content, matches)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (video_id, start_ms) DO UPDATE
    SET end_ms  = EXCLUDED.end_ms,
        content = EXCLUDED.content,
        matches = EXCLUDED.matches
`

type UpsertSegmentResultParams struct {
	VideoID string
	StartMs int64
	EndMs   int64
	Content string
	Matches []byte
}

func (q *Queries) UpsertSegmentResult(ctx context.Context, arg UpsertSegmentResultParams) error {
	_, err := q.db.Exec(ctx, upsertSegmentResult,
		arg.VideoID,
		arg.StartMs,
		arg.EndMs,
		arg.Content,
		arg.Matches,
	)
	return err
}
