// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Named arg query_embedding is referenced twice but sqlc collapses it to a
	// single parameter, so the HNSW index still drives the ORDER BY (no repeated
	// positional-parameter mis-numbering).
	SearchClaims(ctx context.Context, arg SearchClaimsParams) ([]SearchClaimsRow, error)
	UpsertClaim(ctx context.Context, arg []UpsertClaimParams) *UpsertClaimBatchResults
}

var _ Querier = (*Queries)(nil)
