// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Transaction-scoped advisory lock serializing source claims, so two concurrent
	// syncs cannot both pass the foreign-source check and claim different sources.
	// Released automatically at commit/rollback.
	AcquireEvidenceSourceLock(ctx context.Context, key int64) error
	// Claims the store for a source before ingestion starts (and before any
	// checkpoint exists), so a source switch is detectable even after a crashed
	// first run. Never overwrites an existing checkpoint.
	ClaimEvidenceSource(ctx context.Context, source string) error
	CountEvidenceChunksForDocument(ctx context.Context, arg CountEvidenceChunksForDocumentParams) (int64, error)
	// The delta-sync bulk-recommendation denominator counts only the encyclopedic
	// corpora: every statistical source (separate sources that share this table) is
	// excluded so its rows never skew the change-fraction guard. A document is one
	// (source, external_id).
	CountEvidenceDocuments(ctx context.Context, excludeSources []string) (int64, error)
	// The id is caller-minted (the object key embeds it), unlike videos whose id
	// the database assigns.
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	// Insert a pending YouTube ingest. source_id is the canonical video id; the
	// unique constraint makes a repeat submission a no-op, so DO NOTHING returns no
	// row and the caller resolves the existing record by source id instead.
	CreateYouTubeVideo(ctx context.Context, arg CreateYouTubeVideoParams) (Video, error)
	// Sentences and claims go with the document via ON DELETE CASCADE.
	DeleteDocument(ctx context.Context, id uuid.UUID) (int64, error)
	// Delta sync removes a hard-deleted page by title within its own source:
	// RecentChanges reports a deletion with page id 0, so the stored chunk can only
	// be found by its title. Scoping to the source keeps a same-titled chunk of
	// another source safe.
	DeleteEvidenceByTitle(ctx context.Context, arg DeleteEvidenceByTitleParams) error
	DeleteEvidenceDocument(ctx context.Context, arg DeleteEvidenceDocumentParams) error
	// The clustering job reads the embedded live corpus in keyset order to group it
	// into topic clusters and score importance. The embedding IS NOT NULL filter
	// scopes the scan to the chunks that actually carry a vector to cluster, and the
	// source filter keeps statistical evidence (separate sources sharing this table)
	// out of the encyclopedic clustering it does not belong to.
	EmbeddedEvidenceChunks(ctx context.Context, arg EmbeddedEvidenceChunksParams) ([]EmbeddedEvidenceChunksRow, error)
	GetDocument(ctx context.Context, id uuid.UUID) (Document, error)
	GetEvidenceChunk(ctx context.Context, arg GetEvidenceChunkParams) (GetEvidenceChunkRow, error)
	GetEvidenceSyncState(ctx context.Context, source string) (EvidenceSyncState, error)
	GetOtherEvidenceSource(ctx context.Context, source string) (string, error)
	GetVideo(ctx context.Context, id uuid.UUID) (Video, error)
	GetVideoBySourceID(ctx context.Context, sourceID pgtype.Text) (Video, error)
	InsertDocumentSentence(ctx context.Context, arg []InsertDocumentSentenceParams) *InsertDocumentSentenceBatchResults
	// ordinal, not created_at, carries insertion order: an analysis run writes its
	// claims in one transaction, so their created_at values are identical.
	ListDocumentClaims(ctx context.Context, documentID uuid.UUID) ([]ListDocumentClaimsRow, error)
	ListDocumentSentences(ctx context.Context, documentID uuid.UUID) ([]DocumentSentence, error)
	// Library rows, newest first, each with its verdict summary counts. The FILTER
	// counts read stored claims only; a document with no claims counts zero.
	// sqlc.embed keeps the row a real db.Document, so a future documents column
	// cannot silently drop out of the list mapping.
	ListDocuments(ctx context.Context) ([]ListDocumentsRow, error)
	ListVideos(ctx context.Context) ([]Video, error)
	// The voting adapter answers "how did person X vote on bill Y around date Z". The
	// predicate order matches voting_records_person_bill_date_idx. The date is an
	// exact match on the recorded scrutin date; a caller resolves the scrutin date
	// before lookup.
	LookupVotingRecords(ctx context.Context, arg LookupVotingRecordsParams) ([]LookupVotingRecordsRow, error)
	// Atomically claim a failed ingest for retry: flip it back to pending only if it
	// is currently failed, so two concurrent re-submissions cannot both re-download.
	// The guard returns no row (and thus no claim) when the record is not failed.
	RetryFailedVideo(ctx context.Context, id uuid.UUID) (Video, error)
	// Named arg query_embedding is referenced twice but sqlc collapses it to a
	// single parameter, so the HNSW index still drives the ORDER BY (no repeated
	// positional-parameter mis-numbering).
	SearchClaims(ctx context.Context, arg SearchClaimsParams) ([]SearchClaimsRow, error)
	// Approximate nearest-neighbor retrieval over the embedded corpus, mirroring
	// SearchClaims. The embedding IS NOT NULL filter keeps unembedded chunks out of
	// the result regardless of the chosen plan; the HNSW index only indexes
	// non-null rows, so the filter does not degrade index use. query_embedding is
	// referenced twice but sqlc collapses it to one parameter, so the index still
	// drives the ORDER BY.
	SearchEvidenceChunks(ctx context.Context, arg SearchEvidenceChunksParams) ([]SearchEvidenceChunksRow, error)
	// Approximate nearest-neighbor retrieval over the curated political claim DB,
	// mirroring SearchClaims: the fast path borrows an instant verdict for a repeated
	// talking point. query_embedding is referenced twice but sqlc collapses it to one
	// parameter, so the HNSW index drives the ORDER BY.
	SearchPoliticalClaims(ctx context.Context, arg SearchPoliticalClaimsParams) ([]SearchPoliticalClaimsRow, error)
	// Flip a pending document to ready with its extraction metadata. The status
	// guard makes extraction exactly-once: a non-pending document returns no row
	// and the store maps that to a conflict.
	SetDocumentExtracted(ctx context.Context, arg SetDocumentExtractedParams) (Document, error)
	// The clustering job writes each chunk's cluster id and importance into the
	// metadata jsonb, merging with the || operator so the revision id and section
	// keys survive. The casts pin the params to plain integer/double so a non-null
	// write is a value, not a nullable pointer.
	SetEvidenceChunkClustering(ctx context.Context, arg []SetEvidenceChunkClusteringParams) *SetEvidenceChunkClusteringBatchResults
	// Delta sync writes embeddings straight into the live table: at delta volume the
	// HNSW index absorbs the inserts incrementally, so no staging swap is needed.
	SetEvidenceChunkEmbedding(ctx context.Context, arg []SetEvidenceChunkEmbeddingParams) *SetEvidenceChunkEmbeddingBatchResults
	// A failed ingest: record the reason and flip the record to failed.
	SetVideoFailed(ctx context.Context, arg SetVideoFailedParams) (Video, error)
	// A completed ingest: record the probed title, size, and duration, clear any
	// prior error, and flip the record to ready.
	SetVideoReady(ctx context.Context, arg SetVideoReadyParams) (Video, error)
	SetVideoStatus(ctx context.Context, arg SetVideoStatusParams) (Video, error)
	// Delta sync diffs the revision RecentChanges reports against the one stored, so
	// a document already at that revision is neither refetched nor re-embedded. A
	// document's chunks share a revision after an upsert; max guards a partial
	// update. revision_id lives in the metadata jsonb now (a wiki-source key), so a
	// row missing the key yields NULL from the ->> and COALESCE floors it to 0 - a
	// non-numeric revision the delta always treats as stale and refetches, rather
	// than a NULL that would fail the non-nullable int64 scan and stall the sync.
	StoredEvidenceRevisions(ctx context.Context, arg StoredEvidenceRevisionsParams) ([]StoredEvidenceRevisionsRow, error)
	// Removes the stale tail of a document after a re-sync produced fewer chunks
	// (from_index 0 removes the document entirely, e.g. it became a redirect).
	TrimEvidenceDocumentChunks(ctx context.Context, arg []TrimEvidenceDocumentChunksParams) *TrimEvidenceDocumentChunksBatchResults
	// The delta sync reads the chunks it just upserted into the live table back in
	// keyset order to embed them in place. The embedding IS NULL filter scopes the
	// scan to the unembedded chunks a delta run produced. The keyset spans the full
	// (source, external_id, chunk_index) because external_id is unique only within a
	// source.
	UnembeddedEvidenceChunks(ctx context.Context, arg UnembeddedEvidenceChunksParams) ([]UnembeddedEvidenceChunksRow, error)
	UpsertClaim(ctx context.Context, arg []UpsertClaimParams) *UpsertClaimBatchResults
	// Crawl ingestion writes content and embedding together: the worker embeds the
	// self-contained message, then upserts the whole row in one statement so a chunk
	// is never visible to search without its matching vector. The embedding is always
	// the freshly computed one, so a re-crawl rewrites the same vector idempotently.
	UpsertEmbeddedEvidenceChunk(ctx context.Context, arg UpsertEmbeddedEvidenceChunkParams) error
	// Ingest never writes embeddings; the CASE keeps an existing embedding only
	// while the content it was computed from is unchanged, so re-ingesting a
	// changed revision invalidates the stale vector instead of serving it. metadata
	// MERGES (`existing || new`) rather than replacing, so the ingest keys the
	// writer supplies (revision id, section) overwrite while the offline clustering
	// keys (cluster_id, importance) the ingest does not carry survive a re-ingest -
	// the old schema kept importance in a dedicated column the upsert never touched,
	// and UnembeddedLive reads that importance to embed the most important content
	// first.
	UpsertEvidenceChunk(ctx context.Context, arg []UpsertEvidenceChunkParams) *UpsertEvidenceChunkBatchResults
	UpsertEvidenceSyncState(ctx context.Context, arg UpsertEvidenceSyncStateParams) error
	// The fact-check-archive crawler writes a curated claim with its embedding in one
	// statement, so a row is never visible to ANN search without its matching vector.
	// The embedding is the freshly computed one, so a re-crawl rewrites the same row
	// idempotently. The embedding is bound text-form (::halfvec via the pgvector
	// Valuer), never binary COPY.
	UpsertPoliticalClaim(ctx context.Context, arg UpsertPoliticalClaimParams) error
	// size_bytes keeps a known size against a zero reseed: an offline reseed with no
	// cached media seeds the record with size 0, which must not clobber the real
	// size recorded when the media was last uploaded (the object still exists).
	UpsertSampleVideo(ctx context.Context, arg UpsertSampleVideoParams) (Video, error)
	// Scrutins ingest writes one recorded position per person per scrutin. Re-running
	// the ingest rewrites the same row, so a bulk re-run is idempotent.
	UpsertVotingRecord(ctx context.Context, arg UpsertVotingRecordParams) error
}

var _ Querier = (*Queries)(nil)
