// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Named arg query_embedding is referenced twice but sqlc collapses it to a
	// single parameter, so the HNSW index still drives the ORDER BY (no repeated
	// positional-parameter mis-numbering).
	SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error)
	UpsertDocument(ctx context.Context, arg []UpsertDocumentParams) *UpsertDocumentBatchResults
}

var _ Querier = (*Queries)(nil)
