// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tv_channels.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTVChannel = `-- name: CreateTVChannel :one
INSERT INTO tv_channels (slug, name, source_kind, source_ref, enabled, archive_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, name, source_kind, source_ref, enabled, archive_enabled, created_at, updated_at
`

type CreateTVChannelParams struct {
	Slug           string
	Name           string
	SourceKind     string
	SourceRef      string
	Enabled        bool
	ArchiveEnabled bool
}

func (q *Queries) CreateTVChannel(ctx context.Context, arg CreateTVChannelParams) (TvChannel, error) {
	row := q.db.QueryRow(ctx, createTVChannel,
		arg.Slug,
		arg.Name,
		arg.SourceKind,
		arg.SourceRef,
		arg.Enabled,
		arg.ArchiveEnabled,
	)
	var i TvChannel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SourceKind,
		&i.SourceRef,
		&i.Enabled,
		&i.ArchiveEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTVChannel = `-- name: DeleteTVChannel :execrows
DELETE FROM tv_channels
WHERE id = $1
`

// Remove one channel by id. The affected-row count lets the store map an unknown
// id (0 rows) to ErrTVChannelNotFound without a prior existence query. Its
// recordings survive: the videos.channel_id FK is ON DELETE SET NULL.
func (q *Queries) DeleteTVChannel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTVChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTVChannel = `-- name: GetTVChannel :one
SELECT id, slug, name, source_kind, source_ref, enabled, archive_enabled, created_at, updated_at
FROM tv_channels
WHERE id = $1
`

func (q *Queries) GetTVChannel(ctx context.Context, id uuid.UUID) (TvChannel, error) {
	row := q.db.QueryRow(ctx, getTVChannel, id)
	var i TvChannel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SourceKind,
		&i.SourceRef,
		&i.Enabled,
		&i.ArchiveEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTVChannels = `-- name: ListTVChannels :many
SELECT id, slug, name, source_kind, source_ref, enabled, archive_enabled, created_at, updated_at
FROM tv_channels
ORDER BY name, id
`

func (q *Queries) ListTVChannels(ctx context.Context) ([]TvChannel, error) {
	rows, err := q.db.Query(ctx, listTVChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TvChannel{}
	for rows.Next() {
		var i TvChannel
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SourceKind,
			&i.SourceRef,
			&i.Enabled,
			&i.ArchiveEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTVChannel = `-- name: UpdateTVChannel :one
UPDATE tv_channels
SET name = $2, source_kind = $3, source_ref = $4, enabled = $5, archive_enabled = $6, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, source_kind, source_ref, enabled, archive_enabled, created_at, updated_at
`

type UpdateTVChannelParams struct {
	ID             uuid.UUID
	Name           string
	SourceKind     string
	SourceRef      string
	Enabled        bool
	ArchiveEnabled bool
}

// Write the mutable fields of an existing channel. slug is immutable (it keys
// storage paths and seeds), so it is not updatable here.
func (q *Queries) UpdateTVChannel(ctx context.Context, arg UpdateTVChannelParams) (TvChannel, error) {
	row := q.db.QueryRow(ctx, updateTVChannel,
		arg.ID,
		arg.Name,
		arg.SourceKind,
		arg.SourceRef,
		arg.Enabled,
		arg.ArchiveEnabled,
	)
	var i TvChannel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SourceKind,
		&i.SourceRef,
		&i.Enabled,
		&i.ArchiveEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTVChannelBySlug = `-- name: UpsertTVChannelBySlug :one
INSERT INTO tv_channels (slug, name, source_kind, source_ref, enabled, archive_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (slug) DO UPDATE
    SET name        = EXCLUDED.name,
        source_kind = EXCLUDED.source_kind,
        source_ref  = EXCLUDED.source_ref,
        updated_at  = now()
RETURNING id, slug, name, source_kind, source_ref, enabled, archive_enabled, created_at, updated_at
`

type UpsertTVChannelBySlugParams struct {
	Slug           string
	Name           string
	SourceKind     string
	SourceRef      string
	Enabled        bool
	ArchiveEnabled bool
}

// Idempotent seed: insert a channel or, when its slug already exists, refresh
// only the descriptive fields. enabled and archive_enabled are intentionally NOT
// overwritten so reseeding never re-arms a channel the operator turned off (or
// disarmed archiving on); the first insert seeds them from the params.
func (q *Queries) UpsertTVChannelBySlug(ctx context.Context, arg UpsertTVChannelBySlugParams) (TvChannel, error) {
	row := q.db.QueryRow(ctx, upsertTVChannelBySlug,
		arg.Slug,
		arg.Name,
		arg.SourceKind,
		arg.SourceRef,
		arg.Enabled,
		arg.ArchiveEnabled,
	)
	var i TvChannel
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SourceKind,
		&i.SourceRef,
		&i.Enabled,
		&i.ArchiveEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
