// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (title, object_key, content_type, size_bytes, status, kind, channel_id, recorded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
`

type CreateVideoParams struct {
	Title       string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Status      string
	Kind        string
	ChannelID   uuid.NullUUID
	RecordedAt  pgtype.Timestamptz
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.Title,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Kind,
		arg.ChannelID,
		arg.RecordedAt,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}

const createYouTubeVideo = `-- name: CreateYouTubeVideo :one
INSERT INTO videos (title, object_key, content_type, size_bytes, status, kind, source_url, source_id, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (source_id) DO NOTHING
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
`

type CreateYouTubeVideoParams struct {
	Title       string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Status      string
	Kind        string
	SourceUrl   pgtype.Text
	SourceID    pgtype.Text
	DurationMs  int64
}

// Insert a pending YouTube ingest. source_id is the canonical video id; the
// unique constraint makes a repeat submission a no-op, so DO NOTHING returns no
// row and the caller resolves the existing record by source id instead.
func (q *Queries) CreateYouTubeVideo(ctx context.Context, arg CreateYouTubeVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createYouTubeVideo,
		arg.Title,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Kind,
		arg.SourceUrl,
		arg.SourceID,
		arg.DurationMs,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :execrows
DELETE FROM videos
WHERE id = $1
`

// Remove one video record by id. The affected-row count lets the store map an
// unknown id (0 rows) to ErrVideoNotFound without a prior existence query.
func (q *Queries) DeleteVideo(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVideo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVideo = `-- name: GetVideo :one
SELECT id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
FROM videos
WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}

const getVideoByObjectKey = `-- name: GetVideoByObjectKey :one
SELECT id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
FROM videos
WHERE object_key = $1
`

// Resolve a video by its storage object key. The key is UNIQUE, so this is the
// idempotency probe for a deterministic-key writer: a repeated request for the
// same recording finds the existing row instead of colliding on the constraint.
func (q *Queries) GetVideoByObjectKey(ctx context.Context, objectKey string) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByObjectKey, objectKey)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}

const getVideoBySourceID = `-- name: GetVideoBySourceID :one
SELECT id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
FROM videos
WHERE source_id = $1
`

func (q *Queries) GetVideoBySourceID(ctx context.Context, sourceID pgtype.Text) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoBySourceID, sourceID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}

const listTVRecordingsBefore = `-- name: ListTVRecordingsBefore :many
SELECT id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
FROM videos
WHERE kind = 'tv' AND recorded_at IS NOT NULL AND recorded_at < $1
ORDER BY recorded_at
`

// Every archived TV recording captured before the cutoff, oldest first, for
// retention pruning. Scoped to kind 'tv' with a real recorded_at so the scan
// touches only recordings and the caller need not filter in Go.
func (q *Queries) ListTVRecordingsBefore(ctx context.Context, recordedAt pgtype.Timestamptz) ([]Video, error) {
	rows, err := q.db.Query(ctx, listTVRecordingsBefore, recordedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceUrl,
			&i.SourceID,
			&i.DurationMs,
			&i.Error,
			&i.ChannelID,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTVRecordingsByChannel = `-- name: ListTVRecordingsByChannel :many
SELECT id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
FROM videos
WHERE kind = 'tv' AND channel_id = $1 AND status = 'ready' AND recorded_at IS NOT NULL
ORDER BY recorded_at DESC
`

// Every ready archived recording for one channel, newest first, for the /tv
// page's recordings strip. Scoped to kind 'tv' with a ready status so it never
// returns uploads, imports, or a still-pending capture; an orphaned recording
// (channel_id nulled by a channel delete) is excluded by the equality match.
func (q *Queries) ListTVRecordingsByChannel(ctx context.Context, channelID uuid.NullUUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, listTVRecordingsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceUrl,
			&i.SourceID,
			&i.DurationMs,
			&i.Error,
			&i.ChannelID,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideos = `-- name: ListVideos :many
SELECT id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
FROM videos
WHERE kind <> 'tv'
ORDER BY created_at DESC, id
`

// The consumption library (GET /api/videos, the /app grid) excludes kind 'tv':
// archived channel recordings are surfaced per-channel on /tv, not mixed into the
// general video library. Individual recordings remain fetchable by id for replay.
func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceUrl,
			&i.SourceID,
			&i.DurationMs,
			&i.Error,
			&i.ChannelID,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryFailedVideo = `-- name: RetryFailedVideo :one
UPDATE videos
SET status = 'pending', error = NULL, updated_at = now()
WHERE id = $1 AND status = 'failed'
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
`

// Atomically claim a failed ingest for retry: flip it back to pending only if it
// is currently failed, so two concurrent re-submissions cannot both re-download.
// The guard returns no row (and thus no claim) when the record is not failed.
func (q *Queries) RetryFailedVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, retryFailedVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}

const setVideoFailed = `-- name: SetVideoFailed :one
UPDATE videos
SET status = 'failed', error = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
`

type SetVideoFailedParams struct {
	ID    uuid.UUID
	Error pgtype.Text
}

// A failed ingest: record the reason and flip the record to failed.
func (q *Queries) SetVideoFailed(ctx context.Context, arg SetVideoFailedParams) (Video, error) {
	row := q.db.QueryRow(ctx, setVideoFailed, arg.ID, arg.Error)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}

const setVideoReady = `-- name: SetVideoReady :one
UPDATE videos
SET status = 'ready', title = $2, size_bytes = $3, duration_ms = $4, error = NULL, updated_at = now()
WHERE id = $1
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
`

type SetVideoReadyParams struct {
	ID         uuid.UUID
	Title      string
	SizeBytes  int64
	DurationMs int64
}

// A completed ingest: record the probed title, size, and duration, clear any
// prior error, and flip the record to ready.
func (q *Queries) SetVideoReady(ctx context.Context, arg SetVideoReadyParams) (Video, error) {
	row := q.db.QueryRow(ctx, setVideoReady,
		arg.ID,
		arg.Title,
		arg.SizeBytes,
		arg.DurationMs,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}

const setVideoStatus = `-- name: SetVideoStatus :one
UPDATE videos
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
`

type SetVideoStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetVideoStatus(ctx context.Context, arg SetVideoStatusParams) (Video, error) {
	row := q.db.QueryRow(ctx, setVideoStatus, arg.ID, arg.Status)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}

const upsertSampleVideo = `-- name: UpsertSampleVideo :one
INSERT INTO videos (title, object_key, content_type, size_bytes, status, kind)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (object_key) DO UPDATE
    SET title        = EXCLUDED.title,
        content_type = EXCLUDED.content_type,
        size_bytes   = CASE WHEN EXCLUDED.size_bytes > 0 THEN EXCLUDED.size_bytes ELSE videos.size_bytes END,
        status       = EXCLUDED.status,
        kind         = EXCLUDED.kind,
        updated_at   = now()
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at
`

type UpsertSampleVideoParams struct {
	Title       string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Status      string
	Kind        string
}

// size_bytes keeps a known size against a zero reseed: an offline reseed with no
// cached media seeds the record with size 0, which must not clobber the real
// size recorded when the media was last uploaded (the object still exists).
func (q *Queries) UpsertSampleVideo(ctx context.Context, arg UpsertSampleVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, upsertSampleVideo,
		arg.Title,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Kind,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
	)
	return i, err
}
