// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (title, object_key, content_type, size_bytes, status, kind)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at
`

type CreateVideoParams struct {
	Title       string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Status      string
	Kind        string
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.Title,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Kind,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at
FROM videos
WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at
FROM videos
ORDER BY created_at DESC, id
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVideoStatus = `-- name: SetVideoStatus :one
UPDATE videos
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at
`

type SetVideoStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetVideoStatus(ctx context.Context, arg SetVideoStatusParams) (Video, error) {
	row := q.db.QueryRow(ctx, setVideoStatus, arg.ID, arg.Status)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSampleVideo = `-- name: UpsertSampleVideo :one
INSERT INTO videos (title, object_key, content_type, size_bytes, status, kind)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (object_key) DO UPDATE
    SET title        = EXCLUDED.title,
        content_type = EXCLUDED.content_type,
        size_bytes   = EXCLUDED.size_bytes,
        status       = EXCLUDED.status,
        kind         = EXCLUDED.kind,
        updated_at   = now()
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at
`

type UpsertSampleVideoParams struct {
	Title       string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Status      string
	Kind        string
}

func (q *Queries) UpsertSampleVideo(ctx context.Context, arg UpsertSampleVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, upsertSampleVideo,
		arg.Title,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Kind,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
