// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video_analyses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeVideoAnalysisStatus = `-- name: CompleteVideoAnalysisStatus :one
UPDATE videos
SET analysis_status = 'complete', analysis_error = '', analyzed_at = now(), analysis_runs = analysis_runs + 1, updated_at = now()
WHERE id = $1
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at, analysis_status, analysis_error, analyzed_at, analysis_runs, analysis_progress_ms
`

// Terminal success: mark the run complete, stamp the completion time, and
// count the run. Paired with UpsertVideoAnalysis in one transaction so the
// status flip and the stored result are atomic.
func (q *Queries) CompleteVideoAnalysisStatus(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, completeVideoAnalysisStatus, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
		&i.AnalysisStatus,
		&i.AnalysisError,
		&i.AnalyzedAt,
		&i.AnalysisRuns,
		&i.AnalysisProgressMs,
	)
	return i, err
}

const failVideoAnalysis = `-- name: FailVideoAnalysis :exec
UPDATE videos
SET analysis_status = 'failed', analysis_error = $2, updated_at = now()
WHERE id = $1
`

type FailVideoAnalysisParams struct {
	ID            uuid.UUID
	AnalysisError string
}

// Terminal failure: record the reason and flip the run to failed so the
// operator can re-analyse. A previously stored analysis is untouched and
// stays readable.
func (q *Queries) FailVideoAnalysis(ctx context.Context, arg FailVideoAnalysisParams) error {
	_, err := q.db.Exec(ctx, failVideoAnalysis, arg.ID, arg.AnalysisError)
	return err
}

const getVideoAnalysis = `-- name: GetVideoAnalysis :one
SELECT video_id, snapshot_version, events, engine, claims_total, claims_credible, claims_disputed, claims_unverifiable, created_at, updated_at
FROM video_analyses
WHERE video_id = $1
`

func (q *Queries) GetVideoAnalysis(ctx context.Context, videoID uuid.UUID) (VideoAnalysis, error) {
	row := q.db.QueryRow(ctx, getVideoAnalysis, videoID)
	var i VideoAnalysis
	err := row.Scan(
		&i.VideoID,
		&i.SnapshotVersion,
		&i.Events,
		&i.Engine,
		&i.ClaimsTotal,
		&i.ClaimsCredible,
		&i.ClaimsDisputed,
		&i.ClaimsUnverifiable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockVideoForAnalysis = `-- name: LockVideoForAnalysis :one
UPDATE videos
SET analysis_status = 'analysing', analysis_progress_ms = 0, analysis_error = '', updated_at = now()
WHERE id = $1 AND status = 'ready' AND analysis_status <> 'analysing'
RETURNING id, title, object_key, content_type, size_bytes, status, kind, created_at, updated_at, source_url, source_id, duration_ms, error, channel_id, recorded_at, analysis_status, analysis_error, analyzed_at, analysis_runs, analysis_progress_ms
`

// Claim a ready video for a fresh analysis run: flip it to analysing (the
// lock), zero the progress position, and clear any prior error - all in one
// guarded update. The guard admits a video that is ready and not already
// analysing (so a none/complete/failed analysis re-runs, a concurrent run is
// excluded). No row returned means the store resolves why (unknown, not
// ready, or already analysing) and maps it to the right error. The previous
// stored analysis is NOT wiped here: it stays readable until the new run
// completes and overwrites it.
func (q *Queries) LockVideoForAnalysis(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, lockVideoForAnalysis, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceUrl,
		&i.SourceID,
		&i.DurationMs,
		&i.Error,
		&i.ChannelID,
		&i.RecordedAt,
		&i.AnalysisStatus,
		&i.AnalysisError,
		&i.AnalyzedAt,
		&i.AnalysisRuns,
		&i.AnalysisProgressMs,
	)
	return i, err
}

const recoverInterruptedVideoAnalyses = `-- name: RecoverInterruptedVideoAnalyses :many
UPDATE videos
SET analysis_status = 'failed', analysis_error = 'interrupted by restart', updated_at = now()
WHERE analysis_status = 'analysing'
RETURNING id
`

// Startup recovery: any video left analysing when the process died is flipped
// to failed with a clear reason. Returns the recovered ids for logging.
func (q *Queries) RecoverInterruptedVideoAnalyses(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, recoverInterruptedVideoAnalyses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVideoAnalysisProgress = `-- name: SetVideoAnalysisProgress :exec
UPDATE videos
SET analysis_progress_ms = $2, updated_at = now()
WHERE id = $1
`

type SetVideoAnalysisProgressParams struct {
	ID                 uuid.UUID
	AnalysisProgressMs int64
}

// Advance the run's audio position. Progress is database state, so it
// survives a refresh and a restart.
func (q *Queries) SetVideoAnalysisProgress(ctx context.Context, arg SetVideoAnalysisProgressParams) error {
	_, err := q.db.Exec(ctx, setVideoAnalysisProgress, arg.ID, arg.AnalysisProgressMs)
	return err
}

const upsertVideoAnalysis = `-- name: UpsertVideoAnalysis :one
INSERT INTO video_analyses (video_id, snapshot_version, events, engine, claims_total, claims_credible, claims_disputed, claims_unverifiable)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (video_id) DO UPDATE
    SET snapshot_version    = EXCLUDED.snapshot_version,
        events              = EXCLUDED.events,
        engine              = EXCLUDED.engine,
        claims_total        = EXCLUDED.claims_total,
        claims_credible     = EXCLUDED.claims_credible,
        claims_disputed     = EXCLUDED.claims_disputed,
        claims_unverifiable = EXCLUDED.claims_unverifiable,
        updated_at          = now()
RETURNING video_id, snapshot_version, events, engine, claims_total, claims_credible, claims_disputed, claims_unverifiable, created_at, updated_at
`

type UpsertVideoAnalysisParams struct {
	VideoID            uuid.UUID
	SnapshotVersion    int32
	Events             []byte
	Engine             []byte
	ClaimsTotal        int32
	ClaimsCredible     int32
	ClaimsDisputed     int32
	ClaimsUnverifiable int32
}

// Persist a completed run's full event stream, one row per video: a
// re-analysis overwrites the previous result atomically (the run counter on
// videos, not rows here, is the history).
func (q *Queries) UpsertVideoAnalysis(ctx context.Context, arg UpsertVideoAnalysisParams) (VideoAnalysis, error) {
	row := q.db.QueryRow(ctx, upsertVideoAnalysis,
		arg.VideoID,
		arg.SnapshotVersion,
		arg.Events,
		arg.Engine,
		arg.ClaimsTotal,
		arg.ClaimsCredible,
		arg.ClaimsDisputed,
		arg.ClaimsUnverifiable,
	)
	var i VideoAnalysis
	err := row.Scan(
		&i.VideoID,
		&i.SnapshotVersion,
		&i.Events,
		&i.Engine,
		&i.ClaimsTotal,
		&i.ClaimsCredible,
		&i.ClaimsDisputed,
		&i.ClaimsUnverifiable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
