// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wiki.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const acquireWikiCorpusLock = `-- name: AcquireWikiCorpusLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Transaction-scoped advisory lock serializing corpus claims, so two
// concurrent syncs cannot both pass the foreign-corpus check and claim
// different corpora. Released automatically at commit/rollback.
func (q *Queries) AcquireWikiCorpusLock(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, acquireWikiCorpusLock, key)
	return err
}

const claimWikiCorpus = `-- name: ClaimWikiCorpus :exec
INSERT INTO wiki_sync_state (corpus) VALUES ($1)
ON CONFLICT (corpus) DO NOTHING
`

// Claims the store for a corpus before ingestion starts (and before any
// checkpoint exists), so a corpus switch is detectable even after a crashed
// first run. Never overwrites an existing checkpoint.
func (q *Queries) ClaimWikiCorpus(ctx context.Context, corpus string) error {
	_, err := q.db.Exec(ctx, claimWikiCorpus, corpus)
	return err
}

const countWikiChunksForPage = `-- name: CountWikiChunksForPage :one
SELECT count(*) FROM wiki_chunks WHERE page_id = $1
`

func (q *Queries) CountWikiChunksForPage(ctx context.Context, pageID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWikiChunksForPage, pageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWikiPages = `-- name: CountWikiPages :one
SELECT count(DISTINCT page_id)::bigint FROM wiki_chunks
`

func (q *Queries) CountWikiPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWikiPages)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWikiPage = `-- name: DeleteWikiPage :exec
DELETE FROM wiki_chunks WHERE page_id = $1
`

func (q *Queries) DeleteWikiPage(ctx context.Context, pageID int64) error {
	_, err := q.db.Exec(ctx, deleteWikiPage, pageID)
	return err
}

const deleteWikiPagesByTitle = `-- name: DeleteWikiPagesByTitle :exec
DELETE FROM wiki_chunks WHERE title = ANY($1::text[])
`

// Delta sync removes a hard-deleted page by title: RecentChanges reports a
// deletion with page id 0, so the stored page can only be found by its title.
func (q *Queries) DeleteWikiPagesByTitle(ctx context.Context, titles []string) error {
	_, err := q.db.Exec(ctx, deleteWikiPagesByTitle, titles)
	return err
}

const embeddedWikiChunks = `-- name: EmbeddedWikiChunks :many
SELECT page_id, chunk_index, embedding
FROM wiki_chunks
WHERE embedding IS NOT NULL
  AND (page_id, chunk_index) > ($1::bigint, $2::integer)
ORDER BY page_id, chunk_index
LIMIT $3
`

type EmbeddedWikiChunksParams struct {
	AfterPageID     int64
	AfterChunkIndex int32
	RowLimit        int32
}

type EmbeddedWikiChunksRow struct {
	PageID     int64
	ChunkIndex int32
	Embedding  *pgvector.HalfVector
}

// The clustering job reads the embedded live corpus in keyset order to group it
// into topic clusters and score importance. The embedding IS NOT NULL filter
// scopes the scan to the chunks that actually carry a vector to cluster.
func (q *Queries) EmbeddedWikiChunks(ctx context.Context, arg EmbeddedWikiChunksParams) ([]EmbeddedWikiChunksRow, error) {
	rows, err := q.db.Query(ctx, embeddedWikiChunks, arg.AfterPageID, arg.AfterChunkIndex, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbeddedWikiChunksRow{}
	for rows.Next() {
		var i EmbeddedWikiChunksRow
		if err := rows.Scan(&i.PageID, &i.ChunkIndex, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOtherWikiCorpus = `-- name: GetOtherWikiCorpus :one
SELECT corpus FROM wiki_sync_state WHERE corpus <> $1 LIMIT 1
`

func (q *Queries) GetOtherWikiCorpus(ctx context.Context, corpus string) (string, error) {
	row := q.db.QueryRow(ctx, getOtherWikiCorpus, corpus)
	var corpus_2 string
	err := row.Scan(&corpus_2)
	return corpus_2, err
}

const getWikiChunk = `-- name: GetWikiChunk :one
SELECT page_id, chunk_index, title, url, revision_id, corpus, content, section, kind, (embedding IS NULL)::boolean AS embedding_is_null
FROM wiki_chunks
WHERE page_id = $1 AND chunk_index = $2
`

type GetWikiChunkParams struct {
	PageID     int64
	ChunkIndex int32
}

type GetWikiChunkRow struct {
	PageID          int64
	ChunkIndex      int32
	Title           string
	Url             string
	RevisionID      int64
	Corpus          string
	Content         string
	Section         string
	Kind            string
	EmbeddingIsNull bool
}

func (q *Queries) GetWikiChunk(ctx context.Context, arg GetWikiChunkParams) (GetWikiChunkRow, error) {
	row := q.db.QueryRow(ctx, getWikiChunk, arg.PageID, arg.ChunkIndex)
	var i GetWikiChunkRow
	err := row.Scan(
		&i.PageID,
		&i.ChunkIndex,
		&i.Title,
		&i.Url,
		&i.RevisionID,
		&i.Corpus,
		&i.Content,
		&i.Section,
		&i.Kind,
		&i.EmbeddingIsNull,
	)
	return i, err
}

const getWikiSyncState = `-- name: GetWikiSyncState :one
SELECT corpus, last_change_ts, dump_version, synced_at
FROM wiki_sync_state
WHERE corpus = $1
`

func (q *Queries) GetWikiSyncState(ctx context.Context, corpus string) (WikiSyncState, error) {
	row := q.db.QueryRow(ctx, getWikiSyncState, corpus)
	var i WikiSyncState
	err := row.Scan(
		&i.Corpus,
		&i.LastChangeTs,
		&i.DumpVersion,
		&i.SyncedAt,
	)
	return i, err
}

const searchWikiChunks = `-- name: SearchWikiChunks :many
SELECT page_id, chunk_index, title, url, content, section, kind, (embedding <=> $1)::float8 AS distance
FROM wiki_chunks
WHERE embedding IS NOT NULL
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchWikiChunksParams struct {
	QueryEmbedding *pgvector.HalfVector
	ResultLimit    int32
}

type SearchWikiChunksRow struct {
	PageID     int64
	ChunkIndex int32
	Title      string
	Url        string
	Content    string
	Section    string
	Kind       string
	Distance   float64
}

// Approximate nearest-neighbor retrieval over the embedded corpus, mirroring
// SearchClaims. The embedding IS NOT NULL filter keeps unembedded chunks out of
// the result regardless of the chosen plan; the HNSW index only indexes
// non-null rows, so the filter does not degrade index use. query_embedding is
// referenced twice but sqlc collapses it to one parameter, so the index still
// drives the ORDER BY.
func (q *Queries) SearchWikiChunks(ctx context.Context, arg SearchWikiChunksParams) ([]SearchWikiChunksRow, error) {
	rows, err := q.db.Query(ctx, searchWikiChunks, arg.QueryEmbedding, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchWikiChunksRow{}
	for rows.Next() {
		var i SearchWikiChunksRow
		if err := rows.Scan(
			&i.PageID,
			&i.ChunkIndex,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Section,
			&i.Kind,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storedWikiRevisions = `-- name: StoredWikiRevisions :many
SELECT page_id, max(revision_id)::bigint AS revision_id
FROM wiki_chunks
WHERE page_id = ANY($1::bigint[])
GROUP BY page_id
`

type StoredWikiRevisionsRow struct {
	PageID     int64
	RevisionID int64
}

// Delta sync diffs the revision RecentChanges reports against the one stored, so
// a page already at that revision is neither refetched nor re-embedded. A page's
// chunks share a revision after an upsert; max guards against a partial update.
func (q *Queries) StoredWikiRevisions(ctx context.Context, pageIds []int64) ([]StoredWikiRevisionsRow, error) {
	rows, err := q.db.Query(ctx, storedWikiRevisions, pageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoredWikiRevisionsRow{}
	for rows.Next() {
		var i StoredWikiRevisionsRow
		if err := rows.Scan(&i.PageID, &i.RevisionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unembeddedWikiChunks = `-- name: UnembeddedWikiChunks :many
SELECT page_id, chunk_index, title, url, revision_id, corpus, content
FROM wiki_chunks
WHERE embedding IS NULL
  AND (page_id, chunk_index) > ($1::bigint, $2::integer)
ORDER BY page_id, chunk_index
LIMIT $3
`

type UnembeddedWikiChunksParams struct {
	AfterPageID     int64
	AfterChunkIndex int32
	RowLimit        int32
}

type UnembeddedWikiChunksRow struct {
	PageID     int64
	ChunkIndex int32
	Title      string
	Url        string
	RevisionID int64
	Corpus     string
	Content    string
}

// The delta sync reads the chunks it just upserted into the live table back in
// keyset order to embed them in place. The embedding IS NULL filter scopes the
// scan to the unembedded chunks a delta run produced.
func (q *Queries) UnembeddedWikiChunks(ctx context.Context, arg UnembeddedWikiChunksParams) ([]UnembeddedWikiChunksRow, error) {
	rows, err := q.db.Query(ctx, unembeddedWikiChunks, arg.AfterPageID, arg.AfterChunkIndex, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnembeddedWikiChunksRow{}
	for rows.Next() {
		var i UnembeddedWikiChunksRow
		if err := rows.Scan(
			&i.PageID,
			&i.ChunkIndex,
			&i.Title,
			&i.Url,
			&i.RevisionID,
			&i.Corpus,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbeddedChunk = `-- name: UpsertEmbeddedChunk :exec
INSERT INTO wiki_chunks (page_id, chunk_index, title, url, revision_id, corpus, content, section, kind, embedding, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (page_id, chunk_index) DO UPDATE
    SET title = EXCLUDED.title,
        url = EXCLUDED.url,
        revision_id = EXCLUDED.revision_id,
        corpus = EXCLUDED.corpus,
        content = EXCLUDED.content,
        section = EXCLUDED.section,
        kind = EXCLUDED.kind,
        embedding = EXCLUDED.embedding,
        synced_at = now()
`

type UpsertEmbeddedChunkParams struct {
	PageID     int64
	ChunkIndex int32
	Title      string
	Url        string
	RevisionID int64
	Corpus     string
	Content    string
	Section    string
	Kind       string
	Embedding  *pgvector.HalfVector
}

// Crawl ingestion writes content and embedding together: the worker embeds the
// self-contained message, then upserts the whole row in one statement so a chunk
// is never visible to search without its matching vector. The embedding is always
// the freshly computed one, so a re-crawl rewrites the same vector idempotently.
func (q *Queries) UpsertEmbeddedChunk(ctx context.Context, arg UpsertEmbeddedChunkParams) error {
	_, err := q.db.Exec(ctx, upsertEmbeddedChunk,
		arg.PageID,
		arg.ChunkIndex,
		arg.Title,
		arg.Url,
		arg.RevisionID,
		arg.Corpus,
		arg.Content,
		arg.Section,
		arg.Kind,
		arg.Embedding,
	)
	return err
}

const upsertWikiSyncState = `-- name: UpsertWikiSyncState :exec
INSERT INTO wiki_sync_state (corpus, last_change_ts, dump_version)
VALUES ($1, $2, $3)
ON CONFLICT (corpus) DO UPDATE
    SET last_change_ts = EXCLUDED.last_change_ts,
        dump_version = EXCLUDED.dump_version,
        synced_at = now()
`

type UpsertWikiSyncStateParams struct {
	Corpus       string
	LastChangeTs pgtype.Timestamptz
	DumpVersion  pgtype.Text
}

func (q *Queries) UpsertWikiSyncState(ctx context.Context, arg UpsertWikiSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertWikiSyncState, arg.Corpus, arg.LastChangeTs, arg.DumpVersion)
	return err
}
