// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wiki.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireWikiCorpusLock = `-- name: AcquireWikiCorpusLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Transaction-scoped advisory lock serializing corpus claims, so two
// concurrent syncs cannot both pass the foreign-corpus check and claim
// different corpora. Released automatically at commit/rollback.
func (q *Queries) AcquireWikiCorpusLock(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, acquireWikiCorpusLock, key)
	return err
}

const claimWikiCorpus = `-- name: ClaimWikiCorpus :exec
INSERT INTO wiki_sync_state (corpus) VALUES ($1)
ON CONFLICT (corpus) DO NOTHING
`

// Claims the store for a corpus before ingestion starts (and before any
// checkpoint exists), so a corpus switch is detectable even after a crashed
// first run. Never overwrites an existing checkpoint.
func (q *Queries) ClaimWikiCorpus(ctx context.Context, corpus string) error {
	_, err := q.db.Exec(ctx, claimWikiCorpus, corpus)
	return err
}

const countWikiChunksForPage = `-- name: CountWikiChunksForPage :one
SELECT count(*) FROM wiki_chunks WHERE page_id = $1
`

func (q *Queries) CountWikiChunksForPage(ctx context.Context, pageID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWikiChunksForPage, pageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWikiPage = `-- name: DeleteWikiPage :exec
DELETE FROM wiki_chunks WHERE page_id = $1
`

func (q *Queries) DeleteWikiPage(ctx context.Context, pageID int64) error {
	_, err := q.db.Exec(ctx, deleteWikiPage, pageID)
	return err
}

const getOtherWikiCorpus = `-- name: GetOtherWikiCorpus :one
SELECT corpus FROM wiki_sync_state WHERE corpus <> $1 LIMIT 1
`

func (q *Queries) GetOtherWikiCorpus(ctx context.Context, corpus string) (string, error) {
	row := q.db.QueryRow(ctx, getOtherWikiCorpus, corpus)
	var corpus_2 string
	err := row.Scan(&corpus_2)
	return corpus_2, err
}

const getWikiChunk = `-- name: GetWikiChunk :one
SELECT page_id, chunk_index, title, url, revision_id, corpus, content, (embedding IS NULL)::boolean AS embedding_is_null
FROM wiki_chunks
WHERE page_id = $1 AND chunk_index = $2
`

type GetWikiChunkParams struct {
	PageID     int64
	ChunkIndex int32
}

type GetWikiChunkRow struct {
	PageID          int64
	ChunkIndex      int32
	Title           string
	Url             string
	RevisionID      int64
	Corpus          string
	Content         string
	EmbeddingIsNull bool
}

func (q *Queries) GetWikiChunk(ctx context.Context, arg GetWikiChunkParams) (GetWikiChunkRow, error) {
	row := q.db.QueryRow(ctx, getWikiChunk, arg.PageID, arg.ChunkIndex)
	var i GetWikiChunkRow
	err := row.Scan(
		&i.PageID,
		&i.ChunkIndex,
		&i.Title,
		&i.Url,
		&i.RevisionID,
		&i.Corpus,
		&i.Content,
		&i.EmbeddingIsNull,
	)
	return i, err
}

const getWikiSyncState = `-- name: GetWikiSyncState :one
SELECT corpus, last_change_ts, dump_version, synced_at
FROM wiki_sync_state
WHERE corpus = $1
`

func (q *Queries) GetWikiSyncState(ctx context.Context, corpus string) (WikiSyncState, error) {
	row := q.db.QueryRow(ctx, getWikiSyncState, corpus)
	var i WikiSyncState
	err := row.Scan(
		&i.Corpus,
		&i.LastChangeTs,
		&i.DumpVersion,
		&i.SyncedAt,
	)
	return i, err
}

const upsertWikiSyncState = `-- name: UpsertWikiSyncState :exec
INSERT INTO wiki_sync_state (corpus, last_change_ts, dump_version)
VALUES ($1, $2, $3)
ON CONFLICT (corpus) DO UPDATE
    SET last_change_ts = EXCLUDED.last_change_ts,
        dump_version = EXCLUDED.dump_version,
        synced_at = now()
`

type UpsertWikiSyncStateParams struct {
	Corpus       string
	LastChangeTs pgtype.Timestamptz
	DumpVersion  pgtype.Text
}

func (q *Queries) UpsertWikiSyncState(ctx context.Context, arg UpsertWikiSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertWikiSyncState, arg.Corpus, arg.LastChangeTs, arg.DumpVersion)
	return err
}
