// Package postgres implements domain.ClaimStore on Postgres + pgvector.
// SQL is generated by sqlc (see ../../queries and ../db); this file owns the
// connection pool and the mapping between domain types and generated rows.
package postgres

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"strconv"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/pgvector/pgvector-go"
	pgxvec "github.com/pgvector/pgvector-go/pgx"

	"github.com/verovec/truth-in-stream/backend/internal/domain"
	"github.com/verovec/truth-in-stream/backend/internal/store/db"
)

// efSearch is the HNSW candidate-list size per query. Higher trades latency for
// recall; 100 is a safe default at the tens-of-millions scale we target.
const efSearch = 100

// Store is a claim store backed by a pgvector-enabled Postgres database.
type Store struct {
	pool    *pgxpool.Pool
	queries *db.Queries
}

// Store satisfies the domain port.
var _ domain.ClaimStore = (*Store)(nil)

// Open builds a connection pool from a libpq DSN and registers the pgvector
// types (and per-session recall knob) on every connection.
func Open(ctx context.Context, dsn string) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("postgres: parse dsn: %w", err)
	}
	cfg.AfterConnect = func(ctx context.Context, c *pgx.Conn) error {
		if err := pgxvec.RegisterTypes(ctx, c); err != nil {
			return fmt.Errorf("postgres: register vector types: %w", err)
		}
		// SET does not accept a bind parameter over the extended protocol, so
		// use set_config (false = session scope) to keep the value parameterized.
		if _, err := c.Exec(ctx, "SELECT set_config('hnsw.ef_search', $1, false)", strconv.Itoa(efSearch)); err != nil {
			return fmt.Errorf("postgres: set ef_search: %w", err)
		}
		return nil
	}

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("postgres: connect: %w", err)
	}
	return &Store{pool: pool, queries: db.New(pool)}, nil
}

// Ping verifies the store is reachable.
func (s *Store) Ping(ctx context.Context) error {
	if err := s.pool.Ping(ctx); err != nil {
		return fmt.Errorf("postgres: ping: %w", err)
	}
	return nil
}

// Upsert inserts or replaces claims by ID in a single batch.
func (s *Store) Upsert(ctx context.Context, claims []domain.Claim) error {
	if len(claims) == 0 {
		return nil
	}

	params := make([]db.UpsertClaimParams, len(claims))
	for i, c := range claims {
		if !c.Verdict.Valid() {
			return fmt.Errorf("postgres: upsert %q: invalid verdict %q", c.ID, c.Verdict)
		}
		if len(c.Embedding) != domain.EmbeddingDim {
			return fmt.Errorf("postgres: upsert %q: embedding has %d dims, want %d", c.ID, len(c.Embedding), domain.EmbeddingDim)
		}
		sources, err := marshalSources(c.Sources)
		if err != nil {
			return fmt.Errorf("postgres: upsert %q: %w", c.ID, err)
		}
		params[i] = db.UpsertClaimParams{
			ID:        c.ID,
			Content:   c.Text,
			Verdict:   string(c.Verdict),
			Sources:   sources,
			Embedding: pgvector.NewHalfVector(c.Embedding),
		}
	}

	// The generated Exec drains every batched statement, reports each error
	// through the callback, and closes the underlying BatchResults itself, so
	// we capture the first error here and do not Close again.
	br := s.queries.UpsertClaim(ctx, params)
	var execErr error
	br.Exec(func(_ int, err error) {
		if err != nil && execErr == nil {
			execErr = err
		}
	})
	if execErr != nil {
		return fmt.Errorf("postgres: upsert: %w", execErr)
	}
	return nil
}

// Search returns the topK claims closest to query by cosine distance.
func (s *Store) Search(ctx context.Context, query []float32, topK int) ([]domain.ClaimMatch, error) {
	if topK <= 0 || topK > math.MaxInt32 {
		return nil, fmt.Errorf("postgres: search: topK %d out of range", topK)
	}
	if len(query) != domain.EmbeddingDim {
		return nil, fmt.Errorf("postgres: search: query has %d dims, want %d", len(query), domain.EmbeddingDim)
	}

	rows, err := s.queries.SearchClaims(ctx, db.SearchClaimsParams{
		QueryEmbedding: pgvector.NewHalfVector(query),
		ResultLimit:    int32(topK),
	})
	if err != nil {
		return nil, fmt.Errorf("postgres: search: %w", err)
	}

	matches := make([]domain.ClaimMatch, 0, len(rows))
	for _, r := range rows {
		sources, err := unmarshalSources(r.Sources)
		if err != nil {
			return nil, fmt.Errorf("postgres: search: claim %q: %w", r.ID, err)
		}
		matches = append(matches, domain.ClaimMatch{
			ID:      r.ID,
			Text:    r.Content,
			Verdict: domain.Verdict(r.Verdict),
			Sources: sources,
			// Cosine distance is in [0,2]; the float32 narrowing is deliberate
			// to match domain.ClaimMatch and is plenty precise for ranking.
			Distance: float32(r.Distance),
		})
	}
	return matches, nil
}

// Close releases the pool, waiting for in-flight queries to finish.
// pgxpool.Pool.Close is itself safe to call once; no extra guarding needed.
func (s *Store) Close() {
	s.pool.Close()
}

// marshalSources encodes domain sources as a jsonb array. A nil slice would
// encode as SQL NULL, but the column is NOT NULL with a '[]' default, so absent
// sources normalize to an empty array.
func marshalSources(sources []domain.Source) ([]byte, error) {
	if sources == nil {
		sources = []domain.Source{}
	}
	raw, err := json.Marshal(sources)
	if err != nil {
		return nil, fmt.Errorf("marshal sources: %w", err)
	}
	return raw, nil
}

// unmarshalSources decodes a claims.sources jsonb value, defaulting to an empty
// slice so consumers never receive nil (a row could hold 'null'::jsonb).
func unmarshalSources(raw []byte) ([]domain.Source, error) {
	sources := []domain.Source{}
	if len(raw) == 0 {
		return sources, nil
	}
	if err := json.Unmarshal(raw, &sources); err != nil {
		return nil, fmt.Errorf("unmarshal sources: %w", err)
	}
	if sources == nil {
		sources = []domain.Source{}
	}
	return sources, nil
}
