// Package postgres implements domain.VectorStore on Postgres + pgvector.
// SQL is generated by sqlc (see ../../queries and ../db); this file owns the
// connection pool and the mapping between domain types and generated rows.
package postgres

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"strconv"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/pgvector/pgvector-go"
	pgxvec "github.com/pgvector/pgvector-go/pgx"

	"github.com/verovec/truth-in-stream/backend/internal/domain"
	"github.com/verovec/truth-in-stream/backend/internal/store/db"
)

// efSearch is the HNSW candidate-list size per query. Higher trades latency for
// recall; 100 is a safe default at the tens-of-millions scale we target.
const efSearch = 100

// Store is a vector store backed by a pgvector-enabled Postgres database.
type Store struct {
	pool    *pgxpool.Pool
	queries *db.Queries
}

// Open builds a connection pool from a libpq DSN and registers the pgvector
// types (and per-session recall knob) on every connection.
func Open(ctx context.Context, dsn string) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("postgres: parse dsn: %w", err)
	}
	cfg.AfterConnect = func(ctx context.Context, c *pgx.Conn) error {
		if err := pgxvec.RegisterTypes(ctx, c); err != nil {
			return fmt.Errorf("postgres: register vector types: %w", err)
		}
		// SET does not accept a bind parameter over the extended protocol, so
		// use set_config (false = session scope) to keep the value parameterized.
		if _, err := c.Exec(ctx, "SELECT set_config('hnsw.ef_search', $1, false)", strconv.Itoa(efSearch)); err != nil {
			return fmt.Errorf("postgres: set ef_search: %w", err)
		}
		return nil
	}

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("postgres: connect: %w", err)
	}
	return &Store{pool: pool, queries: db.New(pool)}, nil
}

// Ping verifies the store is reachable.
func (s *Store) Ping(ctx context.Context) error {
	if err := s.pool.Ping(ctx); err != nil {
		return fmt.Errorf("postgres: ping: %w", err)
	}
	return nil
}

// Upsert inserts or replaces documents by ID in a single batch.
func (s *Store) Upsert(ctx context.Context, docs []domain.Document) error {
	if len(docs) == 0 {
		return nil
	}

	params := make([]db.UpsertDocumentParams, len(docs))
	for i, d := range docs {
		// A nil map would encode as SQL NULL; the column is NOT NULL with a
		// JSON-object default, so normalize absent metadata to an empty object.
		metadata := d.Metadata
		if metadata == nil {
			metadata = map[string]any{}
		}
		raw, err := json.Marshal(metadata)
		if err != nil {
			return fmt.Errorf("postgres: marshal metadata for %q: %w", d.ID, err)
		}
		params[i] = db.UpsertDocumentParams{
			ID:        d.ID,
			Content:   d.Content,
			Metadata:  raw,
			Embedding: pgvector.NewHalfVector(d.Embedding),
		}
	}

	// The generated Exec drains every batched statement, reports each error
	// through the callback, and closes the underlying BatchResults itself, so
	// we capture the first error here and do not Close again.
	br := s.queries.UpsertDocument(ctx, params)
	var execErr error
	br.Exec(func(_ int, err error) {
		if err != nil && execErr == nil {
			execErr = err
		}
	})
	if execErr != nil {
		return fmt.Errorf("postgres: upsert: %w", execErr)
	}
	return nil
}

// Search returns the topK documents closest to query by cosine distance.
func (s *Store) Search(ctx context.Context, query []float32, topK int) ([]domain.Match, error) {
	if topK <= 0 || topK > math.MaxInt32 {
		return nil, fmt.Errorf("postgres: search: topK %d out of range", topK)
	}

	rows, err := s.queries.SearchDocuments(ctx, db.SearchDocumentsParams{
		QueryEmbedding: pgvector.NewHalfVector(query),
		ResultLimit:    int32(topK),
	})
	if err != nil {
		return nil, fmt.Errorf("postgres: search: %w", err)
	}

	matches := make([]domain.Match, 0, len(rows))
	for _, r := range rows {
		// Default to an empty object so consumers never get a nil map (a row
		// could hold 'null'::jsonb, which unmarshals to nil).
		metadata := map[string]any{}
		if len(r.Metadata) > 0 {
			if err := json.Unmarshal(r.Metadata, &metadata); err != nil {
				return nil, fmt.Errorf("postgres: unmarshal metadata for %q: %w", r.ID, err)
			}
		}
		if metadata == nil {
			metadata = map[string]any{}
		}
		matches = append(matches, domain.Match{
			ID:       r.ID,
			Content:  r.Content,
			Metadata: metadata,
			// Cosine distance is in [0,2]; the float32 narrowing is deliberate
			// to match domain.Match and is plenty precise for ranking.
			Distance: float32(r.Distance),
		})
	}
	return matches, nil
}

// Close releases the pool, waiting for in-flight queries to finish.
// pgxpool.Pool.Close is itself safe to call once; no extra guarding needed.
func (s *Store) Close() {
	s.pool.Close()
}
