// Package postgres implements domain.ClaimStore on Postgres + pgvector.
// SQL is generated by sqlc (see ../../queries and ../db); this file owns the
// connection pool and the mapping between domain types and generated rows.
package postgres

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"strconv"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/pgvector/pgvector-go"
	pgxvec "github.com/pgvector/pgvector-go/pgx"

	"github.com/verovec/truth-in-stream/backend/internal/domain"
	"github.com/verovec/truth-in-stream/backend/internal/store/db"
)

// efSearch is the HNSW candidate-list size per query. Higher trades latency for
// recall; 100 is a safe default at the tens-of-millions scale we target.
const efSearch = 100

// Store is a claim store backed by a pgvector-enabled Postgres database.
type Store struct {
	pool    *pgxpool.Pool
	queries *db.Queries
}

// Store satisfies the domain port.
var _ domain.ClaimStore = (*Store)(nil)

// Open builds a connection pool from a libpq DSN and registers the pgvector
// types (and per-session recall knob) on every connection.
func Open(ctx context.Context, dsn string) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("postgres: parse dsn: %w", err)
	}
	cfg.AfterConnect = func(ctx context.Context, c *pgx.Conn) error {
		if err := pgxvec.RegisterTypes(ctx, c); err != nil {
			return fmt.Errorf("postgres: register vector types: %w", err)
		}
		// SET does not accept a bind parameter over the extended protocol, so
		// use set_config (false = session scope) to keep the value parameterized.
		if _, err := c.Exec(ctx, "SELECT set_config('hnsw.ef_search', $1, false)", strconv.Itoa(efSearch)); err != nil {
			return fmt.Errorf("postgres: set ef_search: %w", err)
		}
		return nil
	}

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("postgres: connect: %w", err)
	}
	return &Store{pool: pool, queries: db.New(pool)}, nil
}

// Ping verifies the store is reachable.
func (s *Store) Ping(ctx context.Context) error {
	if err := s.pool.Ping(ctx); err != nil {
		return fmt.Errorf("postgres: ping: %w", err)
	}
	return nil
}

// Upsert inserts or replaces claims by ID in a single batch.
func (s *Store) Upsert(ctx context.Context, claims []domain.Claim) error {
	if len(claims) == 0 {
		return nil
	}

	params := make([]db.UpsertClaimParams, len(claims))
	for i, c := range claims {
		if !c.Verdict.Valid() {
			return fmt.Errorf("postgres: upsert %q: invalid verdict %q", c.ID, c.Verdict)
		}
		if len(c.Embedding) != domain.EmbeddingDim {
			return fmt.Errorf("postgres: upsert %q: embedding has %d dims, want %d", c.ID, len(c.Embedding), domain.EmbeddingDim)
		}
		sources, err := marshalSources(c.Sources)
		if err != nil {
			return fmt.Errorf("postgres: upsert %q: %w", c.ID, err)
		}
		params[i] = db.UpsertClaimParams{
			ID:        c.ID,
			Content:   c.Text,
			Verdict:   string(c.Verdict),
			Sources:   sources,
			Embedding: pgvector.NewHalfVector(c.Embedding),
		}
	}

	if err := firstBatchError(s.queries.UpsertClaim(ctx, params)); err != nil {
		return fmt.Errorf("postgres: upsert: %w", err)
	}
	return nil
}

// batchExecer is the surface shared by every sqlc-generated *BatchResults
// type for :batchexec queries.
type batchExecer interface {
	Exec(func(int, error))
}

// firstBatchError drains a generated batch and returns its first error. The
// generated Exec runs every batched statement, reports each error through the
// callback, and closes the underlying BatchResults itself, so the caller must
// not Close again.
func firstBatchError(br batchExecer) error {
	var execErr error
	br.Exec(func(_ int, err error) {
		if err != nil && execErr == nil {
			execErr = err
		}
	})
	return execErr
}

// searchIterativeScan is the hnsw.iterative_scan mode a filtered search runs
// under. relaxed_order keeps recall high when a WHERE filter (a source scope)
// would otherwise make HNSW under-return the LIMIT. It is applied ONLY to a
// scoped search: an unfiltered search has nothing to under-return, so enabling
// it there would only weaken the strict distance ordering that the top-1
// consumers and the break-on-first-below-threshold match loops rely on, add a
// pgvector >= 0.8.0 dependency to searches that were version-tolerant, and pay a
// transaction round-trip for nothing. hnsw.max_scan_tuples keeps its bounded
// 20000 default, so a scoped scan is capped rather than unbounded.
const searchIterativeScan = "relaxed_order"

// searchTuned runs one vector search with a per-query hnsw.ef_search and,
// for a scoped search, hnsw.iterative_scan applied transaction-locally
// (set_config local=true) so neither leaks onto the pooled connection the way a
// session SET would. It is the one tuned path the three corpus searches share.
// When neither a raised ef_search (efSearch <= 0) nor iterative scan is needed -
// the unfiltered hot path the live matcher and political fast-path take - it
// runs the query straight on the pool with no transaction, exactly as before,
// preserving both the latency and the session-default strict ordering.
func (s *Store) searchTuned(ctx context.Context, efSearch int, iterativeScan bool, run func(q *db.Queries) error) error {
	if efSearch <= 0 && !iterativeScan {
		return run(s.queries)
	}
	return pgx.BeginFunc(ctx, s.pool, func(tx pgx.Tx) error {
		if efSearch > 0 {
			if _, err := tx.Exec(ctx, "SELECT set_config('hnsw.ef_search', $1, true)", strconv.Itoa(efSearch)); err != nil {
				return fmt.Errorf("set ef_search: %w", err)
			}
		}
		if iterativeScan {
			if _, err := tx.Exec(ctx, "SELECT set_config('hnsw.iterative_scan', $1, true)", searchIterativeScan); err != nil {
				return fmt.Errorf("set iterative_scan: %w", err)
			}
		}
		return run(s.queries.WithTx(tx))
	})
}

// Search returns the topK claims closest to query by cosine distance under a
// per-query efSearch (0 keeps the session default). The claims corpus has no
// source scope, so the search stays strictly ordered (no iterative scan).
func (s *Store) Search(ctx context.Context, query []float32, topK, efSearch int) ([]domain.ClaimMatch, error) {
	if topK <= 0 || topK > math.MaxInt32 {
		return nil, fmt.Errorf("postgres: search: topK %d out of range", topK)
	}
	if len(query) != domain.EmbeddingDim {
		return nil, fmt.Errorf("postgres: search: query has %d dims, want %d", len(query), domain.EmbeddingDim)
	}

	var rows []db.SearchClaimsRow
	err := s.searchTuned(ctx, efSearch, false, func(q *db.Queries) error {
		var e error
		rows, e = q.SearchClaims(ctx, db.SearchClaimsParams{
			QueryEmbedding: pgvector.NewHalfVector(query),
			ResultLimit:    int32(topK),
		})
		return e
	})
	if err != nil {
		return nil, fmt.Errorf("postgres: search: %w", err)
	}

	matches := make([]domain.ClaimMatch, 0, len(rows))
	for _, r := range rows {
		sources, err := unmarshalSources(r.Sources)
		if err != nil {
			return nil, fmt.Errorf("postgres: search: claim %q: %w", r.ID, err)
		}
		matches = append(matches, domain.ClaimMatch{
			ID:      r.ID,
			Text:    r.Content,
			Verdict: domain.Verdict(r.Verdict),
			Sources: sources,
			// Cosine distance is in [0,2]; the float32 narrowing is deliberate
			// to match domain.ClaimMatch and is plenty precise for ranking.
			Distance: float32(r.Distance),
		})
	}
	return matches, nil
}

// Close releases the pool, waiting for in-flight queries to finish.
// pgxpool.Pool.Close is itself safe to call once; no extra guarding needed.
func (s *Store) Close() {
	s.pool.Close()
}

// marshalSources encodes domain sources as a jsonb array. A nil slice would
// encode as SQL NULL, but the column is NOT NULL with a '[]' default, so absent
// sources normalize to an empty array.
func marshalSources(sources []domain.Source) ([]byte, error) {
	if sources == nil {
		sources = []domain.Source{}
	}
	raw, err := json.Marshal(sources)
	if err != nil {
		return nil, fmt.Errorf("marshal sources: %w", err)
	}
	return raw, nil
}

// unmarshalSources decodes a claims.sources jsonb value, defaulting to an empty
// slice so consumers never receive nil (a row could hold 'null'::jsonb).
func unmarshalSources(raw []byte) ([]domain.Source, error) {
	sources := []domain.Source{}
	if len(raw) == 0 {
		return sources, nil
	}
	if err := json.Unmarshal(raw, &sources); err != nil {
		return nil, fmt.Errorf("unmarshal sources: %w", err)
	}
	if sources == nil {
		sources = []domain.Source{}
	}
	return sources, nil
}
