name: pr
on:
  pull_request:
jobs:
  frontend-lint:
    if: ${{ hashFiles('stack/frontend/package.json') != '' }}
    uses: ./.github/workflows/_lint.yml
    with: { path: stack/frontend, lang: node }
  frontend-test:
    if: ${{ hashFiles('stack/frontend/package.json') != '' }}
    uses: ./.github/workflows/_test.yml
    with: { path: stack/frontend, lang: node }
  backend-lint:
    if: ${{ hashFiles('stack/backend/go.mod') != '' }}
    uses: ./.github/workflows/_lint.yml
    with: { path: stack/backend, lang: go }
  backend-test:
    if: ${{ hashFiles('stack/backend/go.mod') != '' }}
    uses: ./.github/workflows/_test.yml
    with: { path: stack/backend, lang: go }
